import { useMemo } from "react";
import { AlertTriangle, PackageCheck, Search, ShoppingCart } from "lucide-react";
import { toast } from "sonner";
import { A, Card, Chip, KpiCard } from "../../components/ui";
import { useListRouteState } from "../../components/navigation/useListRouteState";
import { INVENTORY_WARNINGS, type InventoryWarningLevel } from "./warningData";

const levels: Array<"全部" | InventoryWarningLevel> = ["全部", "缺货", "低库存", "低于安全库存", "低于再订货点", "正常"];
const color = (level: InventoryWarningLevel) => level === "缺货" ? A.red : level === "正常" ? A.green : level === "低库存" ? A.orange : A.purple;
const warningListDefaults = { q: "", level: "全部", page: "1", sort: "risk-desc" };

export default function InventoryWarningPage() {
  const { values, setValue } = useListRouteState({ moduleId: "inventory", routeId: "inventory:warnings", defaults: warningListDefaults });
  const { q: search, level } = values;
  const rows = useMemo(() => INVENTORY_WARNINGS.filter((item) => (!search.trim() || [item.sku, item.itemName, item.warehouse].some((value) => value.toLowerCase().includes(search.trim().toLowerCase()))) && (level === "全部" || item.riskLevel === level)), [level, search]);
  return <div className="space-y-4" data-testid="inventory-warning-page">
    <div className="grid grid-cols-3 gap-3"><KpiCard label="缺货" value={String(INVENTORY_WARNINGS.filter((item) => item.riskLevel === "缺货").length)} icon={AlertTriangle} color={A.red} /><KpiCard label="需补货" value={String(INVENTORY_WARNINGS.filter((item) => item.riskLevel !== "正常").length)} icon={ShoppingCart} color={A.orange} /><KpiCard label="正常" value={String(INVENTORY_WARNINGS.filter((item) => item.riskLevel === "正常").length)} icon={PackageCheck} color={A.green} /></div>
    <Card><div className="p-4 flex items-center gap-2" style={{ borderBottom: `1px solid ${A.border}` }}><div className="h-9 px-3 min-w-[280px] flex items-center gap-2 rounded-lg" style={{ background: A.gray6 }}><Search size={13} /><input aria-label="搜索库存预警" className="w-full bg-transparent outline-none fc-body" placeholder="搜索 SKU、商品、仓库" value={search} onChange={(event) => setValue("q", event.target.value)} /></div><select aria-label="预警级别" className="h-9 px-3 rounded-lg fc-body" style={{ border: `1px solid ${A.border}` }} value={level} onChange={(event) => setValue("level", event.target.value)}>{levels.map((item) => <option key={item}>{item}</option>)}</select><span className="ml-auto fc-caption" style={{ color: A.gray2 }}>{rows.length} 条预警</span></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1420px] text-xs"><thead><tr>{["SKU", "商品名称", "仓库", "当前库存", "已预留", "可用库存", "安全库存", "再订货点", "在途数量", "预计可用", "缺口", "覆盖天数", "风险级别", "建议动作", "操作"].map((item) => <th key={item} className="px-3 py-3 text-left" style={{ color: A.gray1 }}>{item}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.sku} style={{ borderTop: `1px solid ${A.border}` }}><td className="px-3 py-3 font-semibold" style={{ color: A.blue }}>{item.sku}</td><td className="px-3 py-3 font-medium">{item.itemName}</td><td className="px-3 py-3">{item.warehouse}</td><td className="px-3 py-3">{item.currentStock}</td><td className="px-3 py-3">{item.reservedQty}</td><td className="px-3 py-3">{item.availableStock}</td><td className="px-3 py-3">{item.safetyStock}</td><td className="px-3 py-3">{item.reorderPoint}</td><td className="px-3 py-3">{item.incomingQty}</td><td className="px-3 py-3">{item.projectedAvailable}</td><td className="px-3 py-3 font-semibold" style={{ color: item.shortageQty ? A.red : A.green }}>{item.shortageQty}</td><td className="px-3 py-3">{item.daysCover} 天</td><td className="px-3 py-3"><Chip label={item.riskLevel} color={color(item.riskLevel)} bg={`${color(item.riskLevel)}16`} /></td><td className="px-3 py-3 max-w-[220px]">{item.suggestedAction}</td><td className="px-3 py-3"><div className="flex gap-1"><button onClick={() => toast("库存明细", { description: `${item.sku} 当前 ${item.currentStock}，可用 ${item.availableStock}` })} className="px-2 py-1 rounded" style={{ background: A.gray6, color: A.blue }}>查看库存</button><button onClick={() => toast("采购在途", { description: item.incomingPurchaseOrders.join("、") || "暂无在途采购" })} className="px-2 py-1 rounded" style={{ background: A.gray6, color: A.blue }}>查看在途采购</button><button onClick={() => toast("受影响销售订单", { description: item.affectedSalesOrders.join("、") || "暂无" })} className="px-2 py-1 rounded" style={{ background: A.gray6, color: A.blue }}>查看销售订单</button><button onClick={() => toast.success("采购申请草稿已生成", { description: `${item.sku} · 仍需人工复核` })} className="px-2 py-1 rounded" style={{ background: "#fff8f0", color: A.orange }}>创建采购申请草稿</button></div></td></tr>)}</tbody></table></div>
    </Card>
  </div>;
}
