import { expect, test } from "@playwright/test";
const user = { id: "report-filter-user", company: "新辰智能制造", name: "张磊", email: "filter@example.com", role: "供应链经理" };
test.beforeEach(async ({ page }) => { await page.addInitScript((profile) => { localStorage.setItem("scm-demo-token", "filter-token"); localStorage.setItem("scm-demo-user", JSON.stringify(profile)); }, user); });
test("one query filters KPI chart details export and survives reload", async ({ page }) => {
  await page.goto("/app/reports/sales");
  const amount = page.getByRole("button", { name: /销售订单金额/ });
  await expect(amount).toBeVisible(); const before = await amount.textContent();
  const beforeRows = await page.locator("tbody tr").count();
  await page.getByLabel("开始日期").fill("2026-05-01");
  await page.getByRole("button", { name: /更多筛选/ }).click();
  await page.getByLabel("客户", { exact: true }).selectOption("华南自动化设备有限公司");
  await expect(page).toHaveURL(/from=2026-05-01/); await expect(page).toHaveURL(/customer=/);
  await expect(amount).not.toHaveText(before || "");
  expect(await page.locator("tbody tr").count()).toBeLessThan(beforeRows);
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: /导出当前明细/ }).click();
  await download;
  await page.reload();
  await expect(page.getByLabel("开始日期")).toHaveValue("2026-05-01");
  await page.getByRole("button", { name: /更多筛选/ }).click();
  await expect(page.getByLabel("客户", { exact: true })).toHaveValue("华南自动化设备有限公司");
});
