import { useEffect, useMemo, useState } from "react";
import { Copy, Plus, Save, ShieldAlert, Users } from "lucide-react";
import { apiJson } from "../../lib/api-client";
import { A, Card } from "../../components/ui";
import { useI18n } from "../../i18n/I18n";

type Permission = { code: string; module: string; resource: string; action: string; riskLevel: string; fieldVisibility: string[] };
type Role = { id: string; roleKey: string; name: string; description?: string; status: string; isDefaultTemplate: boolean; version: number; updatedAt: string; updatedBy?: { id: string; name: string }; permissionCodes: string[]; permissionCount: number; userCount: number; members: Array<{ id: string; name: string; email: string }> };
type User = { id: string; name: string; email: string; status: string; legacyRole: string; roleIds: string[]; roles: Array<{ id: string; name: string }>; warehouseScopes: Array<{ warehouseId: string; accessLevel: string }> };
type Model = { permissionCatalog: Permission[]; roles: Role[]; users: User[]; defaultRoleTemplates: Array<{ roleKey: string; name: string }> };

const field = "w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm";
const button = "inline-flex items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold disabled:opacity-50";
const moduleOrder = ["settings", "procurement", "receiving", "sales", "inventory", "returns", "finance", "audit"];
const moduleLabels: Record<string, [string, string]> = { settings: ["设置", "Settings"], procurement: ["采购与收货", "Procurement"], receiving: ["采购与收货", "Receiving"], sales: ["销售与发货", "Sales & outbound"], inventory: ["库存", "Inventory"], returns: ["退货与隔离", "Returns & quarantine"], finance: ["财务", "Finance"], audit: ["审计", "Audit"] };
const highRisk = new Set(["approve", "post", "reverse", "mark_export_ready", "manage"]);

export default function AuthorizationWorkbench() {
  const { language, formatDateTime } = useI18n();
  const en = language === "en-US";
  const [model, setModel] = useState<Model | null>(null);
  const [selectedId, setSelectedId] = useState("");
  const [draft, setDraft] = useState<Role | null>(null);
  const [notice, setNotice] = useState("");
  const [saving, setSaving] = useState(false);
  const tr = (zh: string, english: string) => en ? english : zh;
  const load = async () => { try { const next = await apiJson<Model>("/api/authorization/roles"); setModel(next); const id = selectedId || next.roles[0]?.id || ""; setSelectedId(id); setDraft(next.roles.find((role) => role.id === id) || null); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : tr("无权访问或加载失败", "Access denied or failed to load")); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { setDraft(model?.roles.find((role) => role.id === selectedId) || null); }, [selectedId, model]);
  const grouped = useMemo(() => moduleOrder.map((module) => ({ module, permissions: model?.permissionCatalog.filter((permission) => permission.module === module) || [] })).filter((group) => group.permissions.length), [model]);
  const selected = model?.roles.find((role) => role.id === selectedId);
  const changed = Boolean(draft && selected && JSON.stringify({ name: draft.name, description: draft.description, status: draft.status, permissionCodes: [...draft.permissionCodes].sort() }) !== JSON.stringify({ name: selected.name, description: selected.description, status: selected.status, permissionCodes: [...selected.permissionCodes].sort() }));
  const toggle = (code: string) => setDraft((current) => current ? { ...current, permissionCodes: current.permissionCodes.includes(code) ? current.permissionCodes.filter((item) => item !== code) : [...current.permissionCodes, code] } : current);
  const save = async () => { if (!draft) return; setSaving(true); try { await apiJson(`/api/authorization/roles/${encodeURIComponent(draft.id)}`, { method: "PATCH", body: JSON.stringify({ name: draft.name, description: draft.description, status: draft.status, permissionCodes: draft.permissionCodes }) }); await load(); setNotice(tr("角色权限已立即生效。", "Role permissions are effective immediately.")); } catch (error) { setNotice(error instanceof Error ? error.message : tr("保存失败", "Save failed")); } finally { setSaving(false); } };
  const create = async (copyFromRoleId?: string) => { const name = window.prompt(tr("角色名称", "Role name"), tr("退货执行员", "Return Operator")); if (!name) return; try { const role = await apiJson<Role>("/api/authorization/roles", { method: "POST", body: JSON.stringify({ name, copyFromRoleId }) }); await load(); setSelectedId(role.id); } catch (error) { setNotice(error instanceof Error ? error.message : tr("创建失败", "Create failed")); } };
  const assign = async (user: User, roleId: string, enabled: boolean) => { const roleIds = enabled ? [...new Set([...user.roleIds, roleId])] : user.roleIds.filter((id) => id !== roleId); try { await apiJson(`/api/authorization/users/${encodeURIComponent(user.id)}/roles`, { method: "PUT", body: JSON.stringify({ roleIds }) }); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : tr("分配失败", "Assignment failed")); } };
  if (!model) return <Card className="p-6" data-testid="authorization-workbench">{notice || tr("正在加载用户与角色…", "Loading users and roles…")}</Card>;
  return <div className="space-y-5" data-testid="authorization-workbench">
    <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{tr("用户与角色", "Users & roles")}</h2><p className="mt-1 text-sm text-slate-500">{tr("角色名称可自定义；Permission Code 由 FlowChain 管理。操作权限仍需相应仓库的数据范围。", "Role names are tenant-defined; Permission Codes are managed by FlowChain. Action permission still requires the matching warehouse scope.")}</p></div><button data-testid="create-role" className={`${button} text-white`} style={{ background: A.blue }} onClick={() => void create()}><Plus size={15}/>{tr("创建角色", "Create role")}</button></div>{notice && <div role="status" className="mt-3 rounded-lg bg-slate-50 p-3 text-sm">{notice}</div>}</Card>
    <div className="grid gap-5 xl:grid-cols-[390px_1fr]">
      <Card className="overflow-hidden"><div className="border-b p-4 font-semibold">{tr("角色列表", "Role list")}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">{tr("角色", "Role")}</th><th>{tr("用户/权限", "Users/perms")}</th><th>{tr("状态", "Status")}</th></tr></thead><tbody>{model.roles.map((role) => <tr key={role.id} className={`cursor-pointer border-t ${selectedId === role.id ? "bg-blue-50" : ""}`} onClick={() => setSelectedId(role.id)}><td className="p-3"><div className="font-medium">{role.name}</div><div className="text-xs text-slate-500">{role.isDefaultTemplate ? tr("默认模板", "Default template") : role.roleKey}<br/>{formatDateTime(role.updatedAt)} · {role.updatedBy?.name || "—"}</div></td><td>{role.userCount} / {role.permissionCount}</td><td>{role.status === "active" ? tr("启用", "Active") : tr("停用", "Inactive")}</td></tr>)}</tbody></table></div></Card>
      {draft && <Card className="p-5"><div className="flex flex-wrap justify-between gap-3"><div className="grid min-w-[280px] flex-1 gap-3 md:grid-cols-2"><label className="text-sm">{tr("角色名称", "Role name")}<input className={`${field} mt-1`} value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/></label><label className="text-sm">{tr("状态", "Status")}<select className={`${field} mt-1`} value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })}><option value="active">{tr("启用", "Active")}</option><option value="inactive">{tr("停用", "Inactive")}</option></select></label><label className="text-sm md:col-span-2">{tr("描述", "Description")}<textarea className={`${field} mt-1`} value={draft.description || ""} onChange={(event) => setDraft({ ...draft, description: event.target.value })}/></label></div><div className="flex items-start gap-2"><button className={`${button} border bg-white`} onClick={() => void create(draft.id)}><Copy size={14}/>{tr("复制模板", "Copy role")}</button><button data-testid="save-role" className={`${button} text-white`} style={{ background: A.blue }} disabled={!changed || saving} onClick={() => void save()}><Save size={14}/>{tr("保存", "Save")}</button></div></div>
        <div className="mt-5"><h3 className="font-semibold">{tr("Permission Group Matrix", "Permission Group Matrix")}</h3><div className="mt-3 grid gap-4 lg:grid-cols-2">{grouped.map((group) => <section key={group.module} className="rounded-xl border p-4"><h4 className="font-semibold">{moduleLabels[group.module]?.[en ? 1 : 0] || group.module}</h4><div className="mt-2 space-y-2">{group.permissions.map((permission) => <label key={permission.code} className="flex items-start gap-2 text-sm"><input type="checkbox" checked={draft.permissionCodes.includes(permission.code)} onChange={() => toggle(permission.code)}/><span><code className="text-xs">{permission.code}</code>{highRisk.has(permission.action) && <span className="ml-2 rounded bg-rose-100 px-1.5 py-0.5 text-[10px] font-semibold text-rose-700"><ShieldAlert className="mr-1 inline" size={11}/>{permission.action.replaceAll("_", " ").toUpperCase()}</span>}{permission.fieldVisibility.length > 0 && <span className="ml-2 rounded bg-amber-100 px-1.5 py-0.5 text-[10px] text-amber-800">{tr("敏感字段", "Sensitive field")}</span>}</span></label>)}</div></section>)}</div></div>
        <div className="mt-5 rounded-xl bg-slate-50 p-4"><h3 className="font-semibold">{tr("模块可见性预览", "Module visibility preview")}</h3><div className="mt-2 flex flex-wrap gap-2">{moduleOrder.map((module) => { const visible = model.permissionCatalog.some((permission) => permission.module === module && (permission.action === "read" || permission.action === "manage") && draft.permissionCodes.includes(permission.code)); return <span key={module} className={`rounded-full px-3 py-1 text-xs ${visible ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-500"}`}>{moduleLabels[module]?.[en ? 1 : 0] || module}</span>; })}</div></div>
      </Card>}
    </div>
    <Card className="p-5"><h3 className="flex items-center gap-2 font-semibold"><Users size={17}/>{tr("用户分配与有效权限", "User assignment & effective permissions")}</h3><p className="mt-1 text-sm text-slate-500">{tr("Role Assignment 与 Warehouse Scope 分开编辑。拥有操作权限仍需相应仓库的数据范围。", "Role Assignment and Warehouse Scope are edited separately. Action permission still requires the corresponding warehouse data scope.")}</p><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-2">{tr("用户", "User")}</th>{model.roles.map((role) => <th className="p-2" key={role.id}>{role.name}</th>)}<th>{tr("仓库范围", "Warehouse scope")}</th></tr></thead><tbody>{model.users.map((user) => <tr className="border-t" key={user.id}><td className="p-2"><div className="font-medium">{user.name}</div><div className="text-xs text-slate-500">{user.email}</div></td>{model.roles.map((role) => <td className="p-2" key={role.id}><input aria-label={`${user.email} ${role.name}`} type="checkbox" checked={user.roleIds.includes(role.id)} disabled={role.status !== "active"} onChange={(event) => void assign(user, role.id, event.target.checked)}/></td>)}<td className="text-xs">{user.warehouseScopes.map((scope) => `${scope.warehouseId}:${scope.accessLevel}`).join(", ") || tr("无", "None")}</td></tr>)}</tbody></table></div></Card>
  </div>;
}
