import { useEffect, useState } from 'react';
import { Copy, Save, Send, ShieldCheck } from 'lucide-react';
import { apiJson } from '../../lib/api-client';
import { A, Card } from '../../components/ui';

type Profile = { id: string; email: string; name: string; role: string; roleLabel: string; jobTitle?: string; status: string; defaultWarehouseId?: string; profileCompletedAt?: string; version: number; warehouseScopes?: Array<{ warehouseId: string; accessLevel: string }> };
type Workspace = { id: string; name: string; legalName?: string; countryCode: string; baseCurrency: string; timezone: string; workspaceCompletedAt?: string; version: number };
type Warehouse = { id: string; code: string; name: string; status: string };
type User = Profile & { warehouseScopes: Array<{ warehouseId: string; accessLevel: string }> };
type Invitation = { id: string; email: string; role: string; roleLabel: string; status: string; expiresAt: string };
type Diagnostics = { overall: string; generatedAt: string; openingBalanceLocked: boolean; checks: Array<{ id: string; status: 'pass' | 'warn' | 'fail'; detail: string }> };
const field = 'w-full rounded-lg border border-slate-200 px-3 py-2 text-sm';
const button = 'inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold text-white disabled:opacity-50';

export default function PilotWorkspaceSettings({ view }: { view: string }) {
  const [profile, setProfile] = useState<Profile | null>(null); const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [warehouses, setWarehouses] = useState<Warehouse[]>([]); const [users, setUsers] = useState<User[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]);
  const [notice, setNotice] = useState(''); const [inviteEmail, setInviteEmail] = useState(''); const [inviteRole, setInviteRole] = useState('manager'); const [invitePath, setInvitePath] = useState('');
  const [scopeUserId, setScopeUserId] = useState('');
  const [diagnostics, setDiagnostics] = useState<Diagnostics | null>(null);
  async function load() {
    setNotice('');
    try {
      const [p, w, wh] = await Promise.all([apiJson<Profile>('/api/me/profile'), apiJson<Workspace>('/api/workspace'), apiJson<{ warehouses: Warehouse[] }>('/api/workspace/warehouses')]);
      setProfile(p); setWorkspace(w); setWarehouses(wh.warehouses);
      if (p.role === 'admin') {
        const [u, i] = await Promise.all([apiJson<{ users: User[] }>('/api/workspace/users'), apiJson<{ invitations: Invitation[] }>('/api/workspace/invitations')]);
        setUsers(u.users); setInvitations(i.invitations); setScopeUserId(current => current || u.users.find(user => user.role !== 'admin')?.id || u.users[0]?.id || '');
      }
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Pilot settings could not be loaded.'); }
  }
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (view === 'pilot-setup' && profile?.role === 'admin') apiJson<Diagnostics>('/api/admin/pilot-diagnostics').then(setDiagnostics).catch(error => setNotice(error instanceof Error ? error.message : 'Diagnostics failed.')); }, [view, profile?.role]);
  async function saveProfile() { if (!profile) return; try { setProfile(await apiJson<Profile>('/api/me/profile', { method: 'PATCH', body: JSON.stringify(profile) })); setNotice('Profile saved.'); } catch (e) { setNotice(e instanceof Error ? e.message : 'Save failed.'); } }
  async function saveWorkspace() { if (!workspace) return; try { setWorkspace(await apiJson<Workspace>('/api/workspace', { method: 'PATCH', body: JSON.stringify(workspace) })); setNotice('Workspace saved.'); } catch (e) { setNotice(e instanceof Error ? e.message : 'Save failed.'); } }
  async function patchUser(user: User, patch: Partial<User>) { try { await apiJson(`/api/workspace/users/${encodeURIComponent(user.id)}`, { method: 'PATCH', body: JSON.stringify({ ...patch, version: user.version }) }); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'User update failed.'); } }
  async function invite() { try { const result = await apiJson<{ invitationPath: string }>('/api/workspace/invitations', { method: 'POST', body: JSON.stringify({ email: inviteEmail, role: inviteRole, expiryHours: 72 }) }); setInvitePath(result.invitationPath); setInviteEmail(''); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'Invitation failed.'); } }
  async function revokeInvitation(id: string) { try { await apiJson(`/api/workspace/invitations/${encodeURIComponent(id)}/revoke`, { method: 'POST' }); setNotice('Invitation revoked.'); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'Invitation revoke failed.'); } }
  async function saveScopes() { const target = users.find(user => user.id === scopeUserId); if (!target) return; try { await apiJson(`/api/workspace/users/${encodeURIComponent(target.id)}/warehouse-scopes`, { method: 'PUT', body: JSON.stringify({ scopes: target.warehouseScopes }) }); setNotice('Warehouse access saved.'); await load(); } catch (e) { setNotice(e instanceof Error ? e.message : 'Warehouse access failed.'); } }
  if (!profile || !workspace) return <Card className="p-6"><div className="h-40 animate-pulse rounded-xl bg-slate-100" />{notice}</Card>;
  const title = ({ profile: 'My Profile', workspace: 'Workspace', 'pilot-users': 'Users & Invitations', 'warehouse-access': 'Warehouse Access', 'pilot-setup': 'Pilot Setup Status' } as Record<string,string>)[view] || 'Pilot Settings';
  return <Card className="p-5" data-testid={`pilot-settings-${view}`}><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-500">PostgreSQL-backed Pilot workspace settings.</p>{notice && <div className="my-3 rounded-lg bg-slate-50 p-3 text-sm">{notice}</div>}
    {view === 'profile' && <div className="mt-5 grid gap-4 md:grid-cols-2"><label>Name<input className={field} value={profile.name} onChange={e => setProfile({ ...profile, name: e.target.value })}/></label><label>Job title<input className={field} value={profile.jobTitle || ''} onChange={e => setProfile({ ...profile, jobTitle: e.target.value })}/></label><label>Email<input className={`${field} bg-slate-50`} value={profile.email} readOnly/></label><label>Role<input className={`${field} bg-slate-50`} value={profile.roleLabel} readOnly/></label><label>Default warehouse<select className={field} value={profile.defaultWarehouseId || ''} onChange={e => setProfile({ ...profile, defaultWarehouseId: e.target.value })}><option value="">None</option>{warehouses.filter(x => x.status === 'active').map(x => <option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><div className="self-end text-sm">Completion: {profile.profileCompletedAt ? 'Complete' : 'Incomplete'}</div><button onClick={saveProfile} className={`${button} w-fit`} style={{background:A.blue}}><Save size={15}/>Save profile</button></div>}
    {view === 'workspace' && <div className="mt-5 grid gap-4 md:grid-cols-2">{([['name','Workspace name'],['legalName','Legal name'],['countryCode','Country'],['baseCurrency','Base currency'],['timezone','Timezone']] as const).map(([key,label]) => <label key={key}>{label}<input className={field} value={workspace[key] || ''} onChange={e => setWorkspace({ ...workspace, [key]: e.target.value })}/></label>)}<div className="self-end text-sm">Completion: {workspace.workspaceCompletedAt ? 'Complete' : 'Incomplete'}</div>{profile.role === 'admin' ? <button onClick={saveWorkspace} className={`${button} w-fit`} style={{background:A.blue}}><Save size={15}/>Save workspace</button> : <div className="text-sm text-amber-700">Admin only.</div>}</div>}
    {view === 'pilot-users' && <div className="mt-5 space-y-5">{profile.role !== 'admin' ? <div className="text-sm text-amber-700">Admin only.</div> : <><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr>{['User','Email','Role','Status','Warehouse scope'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{users.map(user=><tr className="border-t" key={user.id}><td className="p-2">{user.name}</td><td>{user.email}</td><td><select value={user.role} onChange={e=>void patchUser(user,{role:e.target.value})} className={field}><option value="admin">Admin</option><option value="manager">Manager</option><option value="viewer">Viewer</option><option value="business-specialist">Business specialist</option></select></td><td><select value={user.status} onChange={e=>void patchUser(user,{status:e.target.value})} className={field}><option value="active">Active</option><option value="disabled">Disabled</option></select></td><td>{user.role==='admin'?'All warehouses':user.warehouseScopes.map(x=>`${x.warehouseId}:${x.accessLevel}`).join(', ')||'None'}</td></tr>)}</tbody></table></div><div className="rounded-xl border p-4"><h3 className="font-semibold">Invitation</h3><div className="mt-3 flex flex-wrap gap-2"><input className={`${field} max-w-xs`} placeholder="email@example.com" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/><select className={`${field} w-40`} value={inviteRole} onChange={e=>setInviteRole(e.target.value)}><option value="manager">Manager</option><option value="viewer">Viewer</option><option value="business-specialist">Business specialist</option></select><button onClick={invite} className={button} style={{background:A.blue}}><Send size={15}/>Create invitation</button></div>{invitePath&&<button onClick={()=>void navigator.clipboard.writeText(`${location.origin}${invitePath}`)} className="mt-3 inline-flex items-center gap-2 text-sm text-blue-700"><Copy size={14}/>Copy invitation link</button>}<p className="mt-2 text-xs text-slate-500">Email delivery is not connected in Pilot.</p><div className="mt-3 space-y-2 text-xs">{invitations.map(i=><div className="flex flex-wrap items-center justify-between gap-2" key={i.id}><span>{i.email} · {i.roleLabel} · {i.status} · {new Date(i.expiresAt).toLocaleString()}</span>{i.status==='pending'&&<button className="text-red-600" onClick={()=>void revokeInvitation(i.id)}>Revoke</button>}</div>)}</div></div></>}</div>}
    {view === 'warehouse-access' && <div className="mt-5 overflow-x-auto">{profile.role === 'admin' && <div className="mb-3 flex gap-2"><select className={`${field} max-w-sm`} value={scopeUserId} onChange={e=>setScopeUserId(e.target.value)}>{users.map(user=><option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select><button onClick={saveScopes} className={button} style={{background:A.blue}}><Save size={15}/>Save access</button></div>}<table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Warehouse</th><th>Read / Operate</th><th>Default</th></tr></thead><tbody>{warehouses.map(w=>{const target=profile.role==='admin'?users.find(u=>u.id===scopeUserId):null;const access=profile.role==='admin'&&target?.role==='admin'?'operate':profile.role==='admin'?target?.warehouseScopes.find(s=>s.warehouseId===w.id)?.accessLevel||'':profile.warehouseScopes?.find(s=>s.warehouseId===w.id)?.accessLevel||'';return <tr key={w.id} className="border-t"><td className="p-2">{w.code} · {w.name}</td><td className="text-center">{profile.role==='admin'&&target?.role!=='admin'?<select className={field} value={access} onChange={e=>setUsers(rows=>rows.map(user=>user.id===target?.id?{...user,warehouseScopes:[...user.warehouseScopes.filter(scope=>scope.warehouseId!==w.id),...(e.target.value?[{warehouseId:w.id,accessLevel:e.target.value}]:[])]}:user))}><option value="">No access</option><option value="read">Read</option><option value="operate">Operate</option></select>:access||'No access'}</td><td className="text-center">{(target?.defaultWarehouseId||profile.defaultWarehouseId)===w.id?'Yes':'—'}</td></tr>})}</tbody></table></div>}
    {view === 'pilot-setup' && <div className="mt-5 space-y-4"><div className="grid gap-3 md:grid-cols-3">{[['Profile',!!profile.profileCompletedAt],['Workspace',!!workspace.workspaceCompletedAt],['Warehouse access',profile.role==='admin'||warehouses.length>0]].map(([label,ok])=><div key={String(label)} className="rounded-xl border p-4"><ShieldCheck size={18} color={ok?A.green:A.orange}/><div className="mt-2 font-semibold">{label}</div><div className="text-sm text-slate-500">{ok?'Ready':'Needs setup'}</div></div>)}</div>{profile.role==='admin'&&<div className="rounded-xl border p-4" data-testid="pilot-admin-diagnostics"><div className="flex items-center justify-between"><h3 className="font-semibold">Admin diagnostics</h3><span className="text-xs uppercase" style={{color:diagnostics?.overall==='ready'?A.green:A.orange}}>{diagnostics?.overall||'Loading'}</span></div><p className="mt-1 text-xs text-slate-500">Read-only, safe operational checks. No environment values or secrets are returned.</p><div className="mt-3 grid gap-2 md:grid-cols-2">{diagnostics?.checks.map(check=><div key={check.id} className="rounded-lg bg-slate-50 p-3 text-sm"><span className="font-semibold" style={{color:check.status==='pass'?A.green:check.status==='fail'?A.red:A.orange}}>{check.status.toUpperCase()}</span> · {check.id}<div className="mt-1 text-xs text-slate-500">{check.detail}</div></div>)}</div>{diagnostics&&<div className="mt-3 text-xs text-slate-500">Opening balance locked: {diagnostics.openingBalanceLocked?'Yes':'No'} · Generated {new Date(diagnostics.generatedAt).toLocaleString()}</div>}</div>}</div>}
  </Card>;
}
