import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, FileSpreadsheet, Link2, RefreshCw, RotateCcw, Upload } from "lucide-react";
import { Card } from "../../components/ui";
import { useI18n } from "../../i18n/I18n";
import { apiJson } from "../../lib/api-client";

type Account = { id: string; accountCode: string; name: string; accountType: string; currency: string };
type Mapping = { id: string; templateCode: string; name: string; version: number; cashbookAccountId: string };
type Batch = { id: string; batchNumber: string; fileName: string; fileSha256: string; currency: string; workflowStatus: string; validationStatus: string; totalRowCount: number; acceptedRowCount: number; errorRowCount: number; exactDuplicateRowCount: number; possibleDuplicateRowCount: number; importedLineCount: number; version: number; limitations?: string[] };
type Line = { id: string; transactionDate: string; direction: "credit" | "debit"; amount: string | null; currency: string; counterpartyName: string | null; bankReference: string | null; reconciliationStatus: string; remainingAmount: string | null };
type Candidate = { id: string; cashbookEntryId: string; score: number; candidateType: string; algorithmVersion: string; evidence: Record<string, unknown> };
type Group = { id: string; reconciliationNumber: string; workflowStatus: string; integrityStatus: string; totalBankAmount: string | null; totalCashbookAmount: string | null; differenceAmount: string | null; version: number; conclusion: string };
type Exception = { id: string; exceptionType: string; severity: string; status: string; conclusion: string };
const key = () => crypto.randomUUID();
const body = (value: unknown) => ({ method: "POST", body: JSON.stringify(value) });

export default function BankReconciliationWorkbench({ initialView }: { initialView: "bank-statements" | "bank-reconciliation" }) {
  const { language } = useI18n(); const en = language === "en-US"; const tr = (zh: string, english: string) => en ? english : zh;
  const [accounts, setAccounts] = useState<Account[]>([]), [mappings, setMappings] = useState<Mapping[]>([]), [batches, setBatches] = useState<Batch[]>([]), [lines, setLines] = useState<Line[]>([]), [groups, setGroups] = useState<Group[]>([]), [exceptions, setExceptions] = useState<Exception[]>([]);
  const [accountId, setAccountId] = useState(""), [mappingId, setMappingId] = useState(""), [selectedLineIds, setSelectedLineIds] = useState<string[]>([]), [candidateEntryIds, setCandidateEntryIds] = useState<string[]>([]), [allocationAmount, setAllocationAmount] = useState(""), [candidates, setCandidates] = useState<Record<string, Candidate[]>>({});
  const [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [notice, setNotice] = useState(""), [error, setError] = useState("");
  const selectedAccount = accounts.find((item) => item.id === accountId), selectedLines = lines.filter((item) => selectedLineIds.includes(item.id));

  async function load() {
    const [accountResult, mappingResult, batchResult, lineResult, groupResult, exceptionResult] = await Promise.all([
      apiJson<{ items: Account[] }>("/api/finance/cashbook/accounts"), apiJson<{ items: Mapping[] }>("/api/finance/bank-mappings"), apiJson<{ items: Batch[] }>("/api/finance/bank-statements/batches"), apiJson<{ items: Line[] }>("/api/finance/bank-statements/lines"), apiJson<{ items: Group[] }>("/api/finance/bank-reconciliation/groups"), apiJson<{ items: Exception[] }>("/api/finance/bank-reconciliation/exceptions"),
    ]);
    const eligible = accountResult.items.filter((item) => ["bank", "payment_platform"].includes(item.accountType)); setAccounts(eligible); setMappings(mappingResult.items); setBatches(batchResult.items); setLines(lineResult.items); setGroups(groupResult.items); setExceptions(exceptionResult.items); if (!accountId && eligible[0]) setAccountId(eligible[0].id);
  }
  useEffect(() => { void load().catch((reason) => setError(reason instanceof Error ? reason.message : String(reason))); }, []);
  useEffect(() => { const active = mappings.find((item) => item.cashbookAccountId === accountId); if (active) setMappingId(active.id); }, [accountId, mappings]);
  const act = async (action: () => Promise<void>) => { setBusy(true); setError(""); setNotice(""); try { await action(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };

  async function createDefaultMapping() {
    if (!selectedAccount) return;
    await apiJson("/api/finance/bank-mappings", body({ templateCode: `BANK-${selectedAccount.accountCode}`, name: tr("标准银行流水映射", "Standard bank statement mapping"), bankName: tr("用户选择的银行", "User-selected bank"), formatType: "csv", cashbookAccountId: selectedAccount.id, fileEncoding: "auto_detect", headerRowNumber: 1, firstDataRowNumber: 2, dateFormat: "YYYY-MM-DD", decimalSeparator: ".", thousandsSeparator: ",", debitCreditMode: "signed_amount", signConvention: "positive_credit", timezone: "Asia/Shanghai", columnMapping: { transactionId: "transaction_id", transactionDate: "transaction_date", postingDate: "posting_date", valueDate: "value_date", signedAmount: "signed_amount", currency: "currency", counterpartyName: "counterparty_name", counterpartyAccount: "counterparty_account", description: "description", bankReference: "bank_reference", customerReference: "customer_reference", runningBalance: "running_balance", bankAccountIdentifier: "bank_account_identifier" } })); setNotice(tr("Mapping Template 已创建", "Mapping template created"));
  }
  async function importFile() {
    if (!file || !selectedAccount || !mappingId) throw new Error(tr("请选择账户、Mapping 和文件", "Select an account, mapping, and file"));
    const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (const value of bytes) binary += String.fromCharCode(value);
    const upload = await apiJson<{ uploadId: string }>("/api/finance/bank-statements/uploads", body({ fileName: file.name, mimeType: file.type || (file.name.endsWith(".csv") ? "text/csv" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"), contentBase64: btoa(binary) }));
    let batch = await apiJson<Batch>("/api/finance/bank-statements/batches", body({ cashbookAccountId: selectedAccount.id, mappingTemplateId: mappingId, uploadId: upload.uploadId, currency: selectedAccount.currency, coverageType: "transaction_export" }));
    batch = await apiJson<Batch>(`/api/finance/bank-statements/batches/${encodeURIComponent(batch.id)}/parse`, body({})); batch = await apiJson<Batch>(`/api/finance/bank-statements/batches/${encodeURIComponent(batch.id)}/validate`, body({})); setNotice(tr(`已校验 ${batch.totalRowCount} 行，请复核后 Commit`, `Validated ${batch.totalRowCount} rows; review before commit`));
  }
  async function commitBatch(batch: Batch) { if (!confirm(tr("确认创建不可修改的正式银行流水？", "Create immutable formal bank statement lines?"))) return; await apiJson(`/api/finance/bank-statements/batches/${encodeURIComponent(batch.id)}/commit`, body({ expectedVersion: batch.version, idempotencyKey: key() })); setNotice(tr("银行流水文件已导入", "Bank statement file imported")); }
  async function generate(line: Line) { const result = await apiJson<{ candidates: Candidate[] }>(`/api/finance/bank-reconciliation/lines/${encodeURIComponent(line.id)}/candidates/generate`, body({ dateWindowDays: 3 })); setCandidates((current) => ({ ...current, [line.id]: result.candidates })); setSelectedLineIds([line.id]); if (line.remainingAmount) setAllocationAmount(line.remainingAmount); }
  async function createAndConfirm() {
    if (!selectedAccount || !selectedLines.length || !candidateEntryIds.length || !allocationAmount) throw new Error(tr("请选择流水、Cashbook 候选和分配金额", "Select statement lines, cashbook candidates, and allocation amount"));
    const direction = selectedLines[0].direction, currency = selectedLines[0].currency;
    const group = await apiJson<Group>("/api/finance/bank-reconciliation/groups", body({ cashbookAccountId: selectedAccount.id, currency, direction, reconciliationDate: new Date().toISOString(), bankAllocations: selectedLines.map((line) => ({ bankStatementLineId: line.id, allocatedAmount: selectedLines.length === 1 ? allocationAmount : line.remainingAmount })), cashbookAllocations: candidateEntryIds.map((cashbookEntryId) => ({ cashbookEntryId, allocatedAmount: allocationAmount })) }));
    const preview = await apiJson<{ allowed: boolean; differenceAmount: string; issues: unknown[] }>(`/api/finance/bank-reconciliation/groups/${encodeURIComponent(group.id)}/preview`, body({})); if (!preview.allowed) throw new Error(`${tr("分配未平衡", "Allocations do not balance")}: ${preview.differenceAmount}`); if (!confirm(tr("确认仅建立银行流水匹配关系？不会修改 Cashbook。", "Confirm this evidence relationship? Cashbook will not change."))) return;
    await apiJson(`/api/finance/bank-reconciliation/groups/${encodeURIComponent(group.id)}/confirm`, body({ expectedVersion: group.version, idempotencyKey: key() })); setNotice(tr("已与导入银行流水匹配", "Matched to an imported bank statement")); setSelectedLineIds([]); setCandidateEntryIds([]);
  }
  async function reverse(group: Group) { const reason = prompt(tr("请输入撤销匹配原因", "Enter reconciliation reversal reason")); if (!reason) return; await apiJson(`/api/finance/bank-reconciliation/groups/${encodeURIComponent(group.id)}/reverse`, body({ expectedVersion: group.version, reason })); }

  const summary = useMemo(() => ({ unmatched: lines.filter((item) => item.reconciliationStatus === "unmatched").length, partial: lines.filter((item) => item.reconciliationStatus === "partially_matched").length, matched: lines.filter((item) => item.reconciliationStatus === "matched").length, exceptions: exceptions.filter((item) => item.status === "open").length }), [lines, exceptions]);
  return <div className="min-w-0 space-y-4 overflow-x-hidden" data-testid="bank-reconciliation-workbench">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[tr("尚未匹配", "Unmatched"), summary.unmatched], [tr("部分匹配", "Partial"), summary.partial], [tr("已匹配", "Matched"), summary.matched], [tr("证据异常", "Exceptions"), summary.exceptions]].map(([label, value]) => <Card className="p-4" key={String(label)}><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-xl font-semibold">{value}</div></Card>)}</div>
    {error && <div role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}{notice && <div role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}
    {initialView === "bank-statements" ? <>
      <Card className="p-4" data-testid="bank-import-wizard"><div className="flex items-center gap-2 font-semibold"><Upload size={17}/>{tr("导入银行流水", "Import statement")}</div><div className="mt-2 text-xs text-slate-500">{tr("选择资金账户 → 上传文件 → 映射字段 → 预览 → 校验 → 重复检查 → Commit", "Account → Upload → Mapping → Preview → Validate → Duplicates → Commit")}</div><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-sm">{tr("资金账户", "Cashbook account")}<select data-testid="bank-account" className="mt-1 w-full rounded-lg border p-2" value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="">-</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.accountCode} · {item.name} · {item.currency}</option>)}</select></label><label className="text-sm">Mapping Template<select data-testid="bank-mapping" className="mt-1 w-full rounded-lg border p-2" value={mappingId} onChange={(event) => setMappingId(event.target.value)}><option value="">-</option>{mappings.filter((item) => item.cashbookAccountId === accountId).map((item) => <option key={item.id} value={item.id}>{item.templateCode} v{item.version}</option>)}</select></label><label className="text-sm">CSV / XLSX<input data-testid="bank-file" className="mt-1 block w-full text-xs" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => setFile(event.target.files?.[0] || null)}/></label></div><div className="mt-4 flex flex-wrap gap-2"><button data-testid="create-bank-mapping" disabled={busy || !selectedAccount} className="rounded-lg border px-3 py-2 text-sm" onClick={() => void act(createDefaultMapping)}>{tr("创建标准 Mapping", "Create mapping")}</button><button data-testid="upload-bank-statement" disabled={busy || !file || !mappingId} className="rounded-lg bg-blue-700 px-3 py-2 text-sm text-white" onClick={() => void act(importFile)}>{tr("上传并校验", "Upload & validate")}</button></div></Card>
      <Card className="overflow-hidden"><div className="border-b p-4 font-semibold"><FileSpreadsheet className="mr-2 inline" size={17}/>{tr("导入批次", "Import batches")}</div><div className="overflow-x-auto"><table className="min-w-[880px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs"><tr>{["Batch", tr("文件", "File"), "SHA-256", tr("行数", "Rows"), "Error", "Exact", "Possible", tr("状态", "Status"), tr("动作", "Action")].map((item) => <th className="p-3" key={item}>{item}</th>)}</tr></thead><tbody>{batches.map((item) => <tr className="border-t" key={item.id}><td className="p-3">{item.batchNumber}</td><td className="p-3">{item.fileName}</td><td className="max-w-32 truncate p-3 font-mono text-xs">{item.fileSha256}</td><td className="p-3">{item.acceptedRowCount}/{item.totalRowCount}</td><td className="p-3">{item.errorRowCount}</td><td className="p-3">{item.exactDuplicateRowCount}</td><td className="p-3">{item.possibleDuplicateRowCount}</td><td className="p-3">{item.workflowStatus} · {item.validationStatus}</td><td className="p-3">{item.workflowStatus === "validated" && <button data-testid="commit-bank-statement" className="rounded border px-2 py-1" onClick={() => void act(() => commitBatch(item))}>Commit</button>}</td></tr>)}</tbody></table></div><div className="border-t p-3 text-xs text-amber-700">{tr("交易明细导出不能证明账户期间余额完整性。", "A transaction export does not prove complete period balances.")}</div></Card>
    </> : <>
      <div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><Card className="min-w-0 p-4"><div className="font-semibold">{tr("未匹配银行流水", "Unmatched bank lines")}</div><div className="mt-3 space-y-2">{lines.filter((item) => ["unmatched", "partially_matched"].includes(item.reconciliationStatus)).map((line) => <label key={line.id} className="block rounded-lg border p-3 text-sm"><div className="flex gap-2"><input type="checkbox" checked={selectedLineIds.includes(line.id)} onChange={() => setSelectedLineIds((current) => current.includes(line.id) ? current.filter((id) => id !== line.id) : [...current, line.id])}/><div className="min-w-0"><div>{line.transactionDate.slice(0,10)} · {line.direction} · {line.amount} {line.currency}</div><div className="truncate text-xs text-slate-500">{line.counterpartyName || "••••"} · {line.bankReference || "-"} · {line.reconciliationStatus}</div></div></div><button data-testid="generate-bank-candidates" className="mt-2 rounded border px-2 py-1 text-xs" onClick={() => void act(() => generate(line))}><RefreshCw className="mr-1 inline" size={12}/>{tr("生成候选", "Generate candidates")}</button></label>)}</div></Card><Card className="min-w-0 p-4"><div className="font-semibold">{tr("候选 Cashbook Entries", "Candidate cashbook entries")}</div><div className="mt-3 space-y-2">{selectedLines.flatMap((line) => candidates[line.id] || []).map((candidate) => <label key={candidate.id} className="block rounded-lg border p-3 text-sm" data-testid="candidate-evidence"><div className="flex gap-2"><input type="checkbox" checked={candidateEntryIds.includes(candidate.cashbookEntryId)} onChange={() => setCandidateEntryIds((current) => current.includes(candidate.cashbookEntryId) ? current.filter((id) => id !== candidate.cashbookEntryId) : [...current, candidate.cashbookEntryId])}/><div><div>{candidate.cashbookEntryId} · {candidate.score}/100</div><div className="text-xs text-slate-500">{candidate.candidateType} · {candidate.algorithmVersion}</div></div></div><div className="mt-2 grid grid-cols-2 gap-1 text-xs text-slate-600">{Object.entries(candidate.evidence).filter(([name]) => !["limitations"].includes(name)).map(([name, value]) => <div key={name}>{name}: {String(value ?? "-")}</div>)}</div></label>)}</div><label className="mt-3 block text-sm">{tr("分配金额", "Allocated amount")}<input data-testid="allocation-amount" className="mt-1 w-full rounded-lg border p-2" value={allocationAmount} onChange={(event) => setAllocationAmount(event.target.value)} placeholder="0.0000"/></label><button data-testid="confirm-bank-reconciliation" disabled={busy} className="mt-3 rounded-lg bg-blue-700 px-3 py-2 text-sm text-white" onClick={() => void act(createAndConfirm)}><Link2 className="mr-1 inline" size={14}/>{tr("预览并确认匹配", "Preview & confirm")}</button></Card></div>
      <Card className="overflow-hidden"><div className="border-b p-4 font-semibold">{tr("对账组与异常", "Groups and exceptions")}</div><div className="grid gap-4 p-4 lg:grid-cols-2"><div className="space-y-2">{groups.map((group) => <div key={group.id} className="rounded-lg border p-3 text-sm"><div className="flex items-center justify-between"><span>{group.reconciliationNumber}</span>{group.integrityStatus === "mismatch" ? <AlertTriangle className="text-rose-600" size={16}/> : <CheckCircle2 className="text-emerald-600" size={16}/>}</div><div className="mt-1 text-xs text-slate-500">{group.conclusion} · {group.totalBankAmount} / {group.totalCashbookAmount} · Δ {group.differenceAmount}</div>{group.workflowStatus === "confirmed" && <button data-testid="reverse-bank-reconciliation" className="mt-2 rounded border border-rose-300 px-2 py-1 text-xs text-rose-700" onClick={() => void act(() => reverse(group))}><RotateCcw className="mr-1 inline" size={12}/>{tr("撤销匹配", "Reverse match")}</button>}</div>)}</div><div className="space-y-2">{exceptions.map((item) => <div key={item.id} className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm"><div>{item.exceptionType} · {item.severity}</div><div className="mt-1 text-xs text-slate-600">{item.conclusion}</div></div>)}</div></div></Card>
    </>}
    <div className="text-xs text-slate-500">{tr("“已匹配”仅表示与用户导入的银行流水建立可审计关系；不表示银行执行付款、资金保证、总账记账或税务完成。", "Matched means an auditable relationship to an imported statement only; it does not mean bank execution, guaranteed funds, general-ledger posting, or tax completion.")}</div>
  </div>;
}
