import { useEffect, useMemo, useState } from "react";
import { BarChart3, Copy, FilePlus2, FolderKanban, Share2, Trash2 } from "lucide-react";
import { useNavigate } from "react-router";
import { toast } from "sonner";
import { A, Card, Chip, SegmentedControl } from "../../components/ui";
import { apiJson } from "../../lib/api-client";
import { cloneSavedReportView, createSavedReportView, deleteSavedReportView, listSavedReportViews, updateSavedReportView, type SavedReportView } from "./governedReports";

type Catalog = { subjects: Array<{ id: string; label: string; detailRoute: string; fields: string[] }>; metrics: Array<{ id: string; label: string; subject: string }>; fields: Record<string, Array<{ key: string; label: string; type: string }>> };
const TABS = [{ label: "标准报表", value: "standard" }, { label: "我的报表", value: "mine" }, { label: "团队共享", value: "team" }, { label: "最近使用", value: "recent" }];
const STANDARD = [
  { name: "逾期采购订单", subject: "purchase_orders", route: "/app/reports/procurement?status=open&overdue=true", type: "采购分析" },
  { name: "销售订单履约", subject: "sales_orders", route: "/app/reports/sales", type: "销售分析" },
  { name: "库存风险", subject: "inventory_balances", route: "/app/reports/inventory?risk=below-safety", type: "库存分析" },
  { name: "待处理发票", subject: "supplier_invoices", route: "/app/reports/finance?overdue=true", type: "结算分析" },
  { name: "供应商绩效", subject: "suppliers", route: "/app/reports/suppliers", type: "供应商分析" },
];

export function ReportLibraryV2() {
  const navigate = useNavigate(); const [tab, setTab] = useState("standard"); const [catalog, setCatalog] = useState<Catalog | null>(null); const [views, setViews] = useState<SavedReportView[]>([]); const [actorRole, setActorRole] = useState("viewer"); const [builder, setBuilder] = useState(false);
  const [subject, setSubject] = useState("purchase_orders"); const [name, setName] = useState(""); const [columns, setColumns] = useState<string[]>(["id", "date", "supplier", "amount", "status"]); const [measures, setMeasures] = useState<string[]>([]); const [visualization, setVisualization] = useState("table");
  const refresh = () => listSavedReportViews().then((result) => { setViews(result.views); setActorRole(result.actor.role); }).catch(() => setViews([]));
  useEffect(() => { apiJson<Catalog>("/api/reports/catalog").then(setCatalog).catch(() => setCatalog(null)); refresh(); }, []);
  useEffect(() => { setColumns((catalog?.fields[subject] || []).slice(0, 5).map((field) => field.key)); setMeasures([]); }, [subject, catalog]);
  const visibleViews = useMemo(() => tab === "mine" ? views.filter((view) => view.visibility === "private") : tab === "team" ? views.filter((view) => view.visibility === "team") : [...views].sort((a, b) => b.lastOpenedAt.localeCompare(a.lastOpenedAt)), [tab, views]);
  const openView = (view: SavedReportView) => { const query = new URLSearchParams(view.filters); query.set("savedView", view.viewId); navigate(`${view.sourceRoute}?${query}`); };
  const create = async () => { if (!name.trim()) return toast.warning("请填写报表名称"); try { await createSavedReportView({ name, description: "基于受控业务主题和字段目录创建", subject, sourceRoute: subject === "sales_orders" ? "/app/reports/sales" : subject === "inventory_balances" ? "/app/reports/inventory" : subject === "supplier_invoices" ? "/app/reports/finance" : subject === "suppliers" ? "/app/reports/suppliers" : "/app/reports/procurement", columns, measures, grouping: [], sorting: [], filters: {}, visualization, visibility: "private" }); setBuilder(false); setName(""); refresh(); toast.success("我的报表已创建"); } catch (error) { toast.error("创建失败", { description: error instanceof Error ? error.message : "请重试" }); } };

  return <div className="space-y-4" data-testid="report-library-v2">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold" style={{ color: A.label }}>报表库</h1><p className="mt-1 text-xs" style={{ color: A.sub }}>受控业务主题、标准模板、我的视图与团队共享报表</p></div><button onClick={() => setBuilder(true)} className="h-9 px-3 rounded-lg text-xs font-semibold text-white" style={{ background: A.blue }}><FilePlus2 size={14} className="inline mr-1" />基于模板创建报表</button></div>
    <Card className="p-3"><SegmentedControl options={TABS} value={tab} onChange={setTab} /></Card>
    {tab === "standard" ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{STANDARD.map((report) => <Card key={report.name} className="p-4"><div className="flex items-start justify-between"><div><Chip label={report.type} color={A.blue} bg="#f0f6ff" /><h2 className="mt-2 text-sm font-semibold">{report.name}</h2><p className="mt-1 text-[11px]" style={{ color: A.sub }}>系统标准报表 · 受控主题 {report.subject} · 当前工作区</p></div><FolderKanban size={17} color={A.blue} /></div><button onClick={() => navigate(report.route)} className="mt-4 text-xs font-semibold" style={{ color: A.blue }}>打开报表</button></Card>)}</div> : visibleViews.length ? <Card><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-xs"><thead><tr>{["报表名称", "业务主题", "创建人", "可见范围", "最近使用", "最近更新", "版本", "操作"].map((header) => <th key={header} className="px-4 py-3 text-left" style={{ color: A.gray1 }}>{header}</th>)}</tr></thead><tbody>{visibleViews.map((view) => <tr key={view.viewId} style={{ borderTop: `1px solid ${A.border}` }}><td className="px-4 py-3 font-semibold">{view.name}</td><td className="px-4 py-3">{view.subject}</td><td className="px-4 py-3">{view.ownerName}</td><td className="px-4 py-3"><Chip label={view.visibility === "team" ? "团队共享" : "私有"} color={view.visibility === "team" ? A.green : A.gray1} bg={view.visibility === "team" ? "#f0faf4" : A.gray6} /></td><td className="px-4 py-3">{new Date(view.lastOpenedAt).toLocaleString("zh-CN")}</td><td className="px-4 py-3">{new Date(view.updatedAt).toLocaleString("zh-CN")}</td><td className="px-4 py-3">v{view.version}</td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={() => openView(view)} style={{ color: A.blue }}>打开</button><button aria-label={`复制 ${view.name}`} onClick={async () => { await cloneSavedReportView(view.viewId); refresh(); toast.success("报表已复制"); }}><Copy size={13} /></button>{["manager", "admin"].includes(actorRole) && <button aria-label={`共享 ${view.name}`} onClick={async () => { await updateSavedReportView(view.viewId, { visibility: view.visibility === "team" ? "private" : "team" }); refresh(); }}><Share2 size={13} /></button>}<button aria-label={`删除 ${view.name}`} onClick={async () => { if (!window.confirm(`删除 ${view.name}？`)) return; await deleteSavedReportView(view.viewId); refresh(); }}><Trash2 size={13} color={A.red} /></button></div></td></tr>)}</tbody></table></div></Card> : <Card className="p-10 text-center"><BarChart3 size={24} className="mx-auto" color={A.gray2} /><div className="mt-3 text-sm font-semibold">当前视图暂无报表</div><div className="mt-1 text-xs" style={{ color: A.sub }}>从标准分析页保存当前筛选，或基于受控模板创建。</div></Card>}
    {builder && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4" role="dialog" aria-label="基于模板创建报表"><Card className="w-full max-w-2xl p-5"><div className="flex items-center justify-between"><div><h2 className="text-base font-semibold">基于模板创建报表</h2><p className="mt-1 text-xs" style={{ color: A.sub }}>选择受控主题、字段、指标与展示方式，不开放任意 SQL 或自由 Join。</p></div><button onClick={() => setBuilder(false)}>×</button></div><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs">业务主题<select value={subject} onChange={(event) => setSubject(event.target.value)} className="mt-1 w-full rounded-lg p-2" style={{ background: A.gray6 }}>{catalog?.subjects.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="text-xs">报表名称<input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-lg p-2" style={{ background: A.gray6 }} placeholder="例如：华东逾期采购订单" /></label><label className="text-xs">展示方式<select value={visualization} onChange={(event) => setVisualization(event.target.value)} className="mt-1 w-full rounded-lg p-2" style={{ background: A.gray6 }}>{["table", "bar", "line", "stacked_bar", "donut"].map((item) => <option key={item}>{item}</option>)}</select></label><div className="text-xs">已选字段<div className="mt-1 flex flex-wrap gap-1">{columns.map((key) => <Chip key={key} label={key} color={A.blue} bg="#f0f6ff" />)}</div></div></div><div className="mt-4"><div className="text-xs font-semibold">选择字段</div><div className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-3">{catalog?.fields[subject]?.map((field) => <label key={field.key} className="text-xs"><input type="checkbox" checked={columns.includes(field.key)} onChange={(event) => setColumns((current) => event.target.checked ? [...current, field.key] : current.filter((key) => key !== field.key))} /> {field.label}</label>)}</div></div><div className="mt-4"><div className="text-xs font-semibold">选择指标</div><div className="mt-2 grid grid-cols-2 gap-2">{catalog?.metrics.filter((metric) => metric.subject === subject).map((metric) => <label key={metric.id} className="text-xs"><input type="checkbox" checked={measures.includes(metric.id)} onChange={(event) => setMeasures((current) => event.target.checked ? [...current, metric.id] : current.filter((key) => key !== metric.id))} /> {metric.label}</label>)}</div></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setBuilder(false)} className="px-3 py-2 text-xs">取消</button><button onClick={create} className="px-4 py-2 rounded-lg text-xs font-semibold text-white" style={{ background: A.blue }}>保存为私有报表</button></div></Card></div>}
  </div>;
}
