import { Copy, Eye, Pencil } from "lucide-react";
import { toast } from "sonner";
import { A, Chip } from "../../components/ui";
import type { CustomerMaster, PrintTemplateCatalogItem } from "./standardData";

export function CustomerTable({ customers }: { customers: CustomerMaster[] }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-xs"><thead><tr>{["客户编号", "客户名称", "联系人", "电话", "地址", "信用状态", "付款条款", "状态", "操作"].map((item) => <th key={item} className="px-4 py-3 text-left" style={{ color: A.gray1 }}>{item}</th>)}</tr></thead><tbody>{customers.map((item) => <tr key={item.code} style={{ borderTop: `1px solid ${A.border}` }}><td className="px-4 py-3 font-semibold" style={{ color: A.blue }}>{item.code}</td><td className="px-4 py-3 font-medium">{item.name}</td><td className="px-4 py-3">{item.contact}</td><td className="px-4 py-3">{item.phone}</td><td className="px-4 py-3 max-w-[260px] truncate">{item.address}</td><td className="px-4 py-3"><Chip label={item.creditStatus} color={item.creditStatus === "正常" ? A.green : item.creditStatus === "受限" ? A.red : A.orange} bg={item.creditStatus === "正常" ? "#f0faf4" : item.creditStatus === "受限" ? "#fff1f0" : "#fff8f0"} /></td><td className="px-4 py-3">{item.paymentTerms}</td><td className="px-4 py-3">{item.status}</td><td className="px-4 py-3"><button className="px-2.5 py-1.5 rounded-md" style={{ background: A.gray6, color: A.blue }}>查看详情</button></td></tr>)}</tbody></table></div>;
}

export function PrintTemplateTable({ templates, onCopy }: { templates: PrintTemplateCatalogItem[]; onCopy: (item: PrintTemplateCatalogItem) => void }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-xs"><thead><tr>{["模板名称", "单据类型", "是否默认", "最近更新时间", "操作"].map((item) => <th key={item} className="px-4 py-3 text-left" style={{ color: A.gray1 }}>{item}</th>)}</tr></thead><tbody>{templates.map((item) => <tr key={item.id} style={{ borderTop: `1px solid ${A.border}` }}><td className="px-4 py-3 font-semibold" style={{ color: A.label }}>{item.name}</td><td className="px-4 py-3">{item.documentType}</td><td className="px-4 py-3"><Chip label={item.isDefault ? "默认" : "自定义"} color={item.isDefault ? A.green : A.blue} bg={item.isDefault ? "#f0faf4" : "#f0f6ff"} /></td><td className="px-4 py-3">{item.updatedAt}</td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={() => toast("请从具体业务单据进入编辑", { description: `${item.name} 会自动绑定当前单据真实数据。` })} className="px-2.5 py-1.5 rounded-md flex items-center gap-1" style={{ background: "#f0f6ff", color: A.blue }}><Pencil size={12} />编辑模板</button><button onClick={() => onCopy(item)} className="px-2.5 py-1.5 rounded-md flex items-center gap-1" style={{ background: A.gray6, color: A.label }}><Copy size={12} />复制模板</button><button onClick={() => toast("模板预览", { description: `${item.name} · ${item.documentType}` })} className="px-2.5 py-1.5 rounded-md flex items-center gap-1" style={{ background: A.gray6, color: A.label }}><Eye size={12} />预览</button></div></td></tr>)}</tbody></table></div>;
}
