import { Copy, Eye } from "lucide-react";
import { A, Chip } from "../../components/ui";
import { BusinessEntityLink } from "../../components/business/BusinessEntityLink";
import type { CustomerMaster, PrintTemplateCatalogItem } from "./standardData";

export function CustomerTable({ customers }: { customers: CustomerMaster[] }) {
  if (customers.length === 0) return <div className="px-6 py-12 text-center text-sm text-slate-500">真实客户主数据为空，请创建或导入客户后再继续。</div>;
  return <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-xs"><thead><tr>{["客户编号", "客户名称", "联系人", "电话", "地址", "信用状态", "付款条款", "状态", "操作"].map((item) => <th key={item} className="px-4 py-3 text-left" style={{ color: A.gray1 }}>{item}</th>)}</tr></thead><tbody>{customers.map((item) => <tr key={item.code} style={{ borderTop: `1px solid ${A.border}` }}><td className="px-4 py-3 font-semibold"><BusinessEntityLink entityType="customer" entityId={item.code}>{item.code}</BusinessEntityLink></td><td className="px-4 py-3 font-medium"><BusinessEntityLink entityType="customer" entityId={item.code}>{item.name}</BusinessEntityLink></td><td className="px-4 py-3">{item.contact}</td><td className="px-4 py-3">{item.phone}</td><td className="px-4 py-3 max-w-[260px] truncate">{item.address}</td><td className="px-4 py-3"><Chip label={item.creditStatus} color={item.creditStatus === "正常" ? A.green : item.creditStatus === "受限" ? A.red : A.orange} bg={item.creditStatus === "正常" ? "#f0faf4" : item.creditStatus === "受限" ? "#fff1f0" : "#fff8f0"} /></td><td className="px-4 py-3">{item.paymentTerms}</td><td className="px-4 py-3">{item.status}</td><td className="px-4 py-3"><BusinessEntityLink entityType="customer" entityId={item.code} className="rounded-md bg-slate-100 px-2.5 py-1.5">查看详情</BusinessEntityLink></td></tr>)}</tbody></table></div>;
}

export function PrintTemplateTable({ templates, onCopy }: { templates: PrintTemplateCatalogItem[]; onCopy: (item: PrintTemplateCatalogItem) => void }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-xs"><thead><tr>{["模板名称", "单据类型", "是否默认", "最近更新时间", "操作"].map((item) => <th key={item} className="px-4 py-3 text-left" style={{ color: A.gray1 }}>{item}</th>)}</tr></thead><tbody>{templates.map((item) => <tr key={item.id} style={{ borderTop: `1px solid ${A.border}` }}><td className="px-4 py-3 font-semibold" style={{ color: A.label }}>{item.name}</td><td className="px-4 py-3">{item.documentType}</td><td className="px-4 py-3"><Chip label={item.isDefault ? "默认" : "自定义"} color={item.isDefault ? A.green : A.blue} bg={item.isDefault ? "#f0faf4" : "#f0f6ff"} /></td><td className="px-4 py-3">{item.updatedAt}</td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={() => onCopy(item)} className="px-2.5 py-1.5 rounded-md flex items-center gap-1" style={{ background: A.gray6, color: A.label }}><Copy size={12} />复制模板</button><details className="relative"><summary className="list-none cursor-pointer px-2.5 py-1.5 rounded-md flex items-center gap-1" style={{ background: A.gray6, color: A.label }}><Eye size={12} />预览</summary><div className="absolute right-0 z-20 mt-1 w-64 rounded-lg border bg-white p-3 shadow-lg"><div className="font-semibold">{item.name}</div><div className="mt-2 text-slate-500">单据类型：{item.documentType}</div><div className="mt-1 text-slate-500">更新时间：{item.updatedAt}</div></div></details></div></td></tr>)}</tbody></table></div>;
}
