import assert from "node:assert/strict";
import test from "node:test";
import { backfillTenantAuthorization } from "../../server/auth/authorization-backfill.mjs";
import { createBankReconciliationEvidenceService } from "../../server/domain/bank-reconciliation-evidence.mjs";
import { createBankReconciliationService } from "../../server/domain/bank-reconciliation-service.mjs";
import { createBankStatementService } from "../../server/domain/bank-statement-service.mjs";
import { createPrismaClient } from "../../server/persistence/prisma-client.mjs";

const tenantId = "tenant-phase-5-3-evidence", userId = "phase-5-3-evidence-admin";
const context = { identity: { authenticated: true, tenantId, userId, role: "admin" } };
const env = { ...process.env, FLOWCHAIN_PERSISTENCE_MODE: "database", FLOWCHAIN_ENABLE_DB_BANK_RECONCILIATION: "true", FLOWCHAIN_ATTACHMENT_STORAGE_PROVIDER: "local" };

test("bank reconciliation evidence independently recomputes recorded conclusions", async () => {
  const prisma = await createPrismaClient(env);
  try {
    await prisma.tenant.create({ data: { id: tenantId, name: "Fictitious Evidence Workspace", currency: "CNY" } }); await prisma.user.create({ data: { id: userId, tenantId, email: "evidence@phase-5-3.invalid", name: "Evidence Admin", role: "admin" } }); await backfillTenantAuthorization(prisma, tenantId, { actorId: userId }); await prisma.cashbookAccount.create({ data: { id: "evidence-account", tenantId, accountCode: "EV-BANK", name: "Evidence Bank", accountType: "bank", currency: "CNY" } });
    const statement = createBankStatementService({ prisma, env }), reconciliation = createBankReconciliationService({ prisma, env });
    const mapping = await statement.createMapping({ templateCode: "EV-MAP", name: "Evidence mapping", formatType: "csv", cashbookAccountId: "evidence-account", fileEncoding: "utf8", debitCreditMode: "signed_amount", signConvention: "positive_credit", timezone: "UTC", headerRowNumber: 1, firstDataRowNumber: 2, columnMapping: { transactionId: "transaction_id", transactionDate: "transaction_date", signedAmount: "signed_amount", currency: "currency", bankReference: "bank_reference" } }, context);
    const bytes = Buffer.from("transaction_id,transaction_date,signed_amount,currency,bank_reference\nEV-1,2026-07-10,75.1250,CNY,EV-REF\n"); const upload = await statement.stageUpload({ fileName: "evidence.csv", mimeType: "text/csv", contentBase64: bytes.toString("base64") }, context); let batch = await statement.createBatch({ cashbookAccountId: "evidence-account", mappingTemplateId: mapping.id, uploadId: upload.uploadId, currency: "CNY" }, context); batch = await statement.parseBatch(batch.id, context); batch = await statement.validateBatch(batch.id, context); await statement.commitBatch(batch.id, { expectedVersion: batch.version, idempotencyKey: "evidence-commit" }, context); const line = (await statement.listLines({}, context)).items[0];
    await prisma.settlementDocument.create({ data: { id: "evidence-settlement", tenantId, settlementNumber: "EV-SET", direction: "receipt", counterpartyType: "customer", cashbookAccountId: "evidence-account", currency: "CNY", amount: line.amount, cashAmount: line.amount, totalSettlementAmount: line.amount, settlementDate: new Date("2026-07-10"), status: "posted", workflowStatus: "posted", postingStatus: "posted", externalReference: "EV-REF" } }); await prisma.cashbookEntry.create({ data: { id: "evidence-entry", tenantId, cashbookAccountId: "evidence-account", settlementId: "evidence-settlement", entryNumber: "EV-CB", entryType: "settlement", direction: "inflow", amount: line.amount, currency: "CNY", occurredAt: new Date("2026-07-10"), balanceBefore: "0", balanceAfter: line.amount, postingBatchId: "ev-post" } });
    await reconciliation.generateCandidates(line.id, {}, context); let group = await reconciliation.createGroup({ cashbookAccountId: "evidence-account", currency: "CNY", direction: "credit", reconciliationDate: "2026-07-10", bankAllocations: [{ bankStatementLineId: line.id, allocatedAmount: line.amount }], cashbookAllocations: [{ cashbookEntryId: "evidence-entry", allocatedAmount: line.amount }] }, context); await reconciliation.confirmGroup(group.id, { expectedVersion: group.version, idempotencyKey: "evidence-confirm" }, context);
    const evidence = createBankReconciliationEvidenceService({ prisma, env, storageProvider: statement.storage }); const result = await evidence.verify(group.id, context); assert.equal(result.reconciliation, "matched"); assert.ok(result.checks.every((row) => row.status === "matched")); assert.ok(result.checks.some((row) => row.name.startsWith("file_hash:"))); assert.ok(result.checks.some((row) => row.name.startsWith("cashbook_source_document:")));
    await prisma.$executeRawUnsafe('ALTER TABLE "BankReconciliationGroup" DISABLE TRIGGER "BankReconciliationGroup_confirmed_immutable"'); await prisma.bankReconciliationGroup.update({ where: { id: group.id }, data: { totalBankAmount: "1.0000" } }); await prisma.$executeRawUnsafe('ALTER TABLE "BankReconciliationGroup" ENABLE TRIGGER "BankReconciliationGroup_confirmed_immutable"'); const mismatch = await evidence.verify(group.id, context); assert.equal(mismatch.reconciliation, "mismatch"); assert.ok(mismatch.checks.some((row) => row.name === "bank_allocation_total" && row.status === "mismatch"));
  } finally { await prisma.$disconnect(); }
});
