import test from 'node:test'; import assert from 'node:assert/strict'; import { mkdtemp, readFile, rm } from 'node:fs/promises'; import { join } from 'node:path'; import { tmpdir } from 'node:os'
import { createDurableProcurementRepository } from '../repositories/durable-procurement-repository.mjs'
import { createProcurementWorkflowService } from '../services/procurement-workflow-service.mjs'
import { recommendProcurementPath, validateDirectPo } from './procurement-workflow.mjs'

async function fixture(policy={}) { const dir=await mkdtemp(join(tmpdir(),'flowchain-proc-')); const file=join(dir,'transactions.json'); const repo=createDurableProcurementRepository({dataFile:file}); const service=createProcurementWorkflowService({repository:repo,policyProvider:async()=>policy}); return {dir,file,repo,service} }
test('durable repository seeds once, writes schema v1 atomically and survives restart', async()=>{ const f=await fixture(); const pr=await f.service.createPurchaseRequest({lines:[{sku:'SKU-1',quantity:2,unit:'件',unitPrice:10}],totalAmount:20},'u1'); assert.equal(pr.status,'draft'); assert.equal(JSON.parse(await readFile(f.file,'utf8')).schemaVersion,1); const restarted=createDurableProcurementRepository({dataFile:f.file,seed:{schemaVersion:1,purchaseRequests:[{id:'SHOULD-NOT-OVERWRITE'}],rfqs:[],purchaseOrders:[],idempotencyRecords:[],auditEntries:[]}}); assert.equal((await restarted.list('pr'))[0].id,pr.id); await rm(f.dir,{recursive:true,force:true}) })
test('PR state machine enforces expectedVersion and legal transitions', async()=>{ const f=await fixture(); const pr=await f.service.createPurchaseRequest({},'u1'); await assert.rejects(()=>f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:1,actor:'manager'}),e=>e.code==='INVALID_STATE_TRANSITION'); const submitted=await f.service.transitionPurchaseRequest(pr.id,'submitted',{expectedVersion:1,actor:'u1'}); assert.equal(submitted.version,2); await assert.rejects(()=>f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:1,actor:'manager'}),e=>e.code==='VERSION_CONFLICT'); assert.equal((await f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:2,actor:'manager'})).status,'approved'); await rm(f.dir,{recursive:true,force:true}) })
test('path recommendation separates status from procurement path and snapshots policy', ()=>{ const direct=recommendProcurementPath({status:'approved',supplierId:'S1',totalAmount:100,lines:[{unitPrice:10}]},{rfqRequiredAboveAmount:1000},{active:true},{valid:true}); assert.equal(direct.recommendation,'direct_po'); const rfq=recommendProcurementPath({status:'approved',totalAmount:2000,lines:[{unitPrice:0}]},{rfqRequiredAboveAmount:1000},{active:true},{valid:false}); assert.equal(rfq.recommendation,'rfq'); assert.equal(rfq.policySnapshot.rfqRequiredByPolicy,true) })
test('direct PO validation returns structured field errors and permission denial', ()=>{ assert.throws(()=>validateDirectPo({status:'approved',procurementPath:'undecided',lines:[]},{},true),e=>e.code==='DIRECT_PO_NOT_ALLOWED'&&e.details.some(x=>x.field==='supplierId')); assert.throws(()=>validateDirectPo({status:'approved'}, {}, false),e=>e.code==='PERMISSION_DENIED') })
test('path decision persists snapshot, requires override reason and locks after downstream object', async()=>{ const f=await fixture({rfqRequiredAboveAmount:100,allowManagerOverride:true}); let pr=await f.service.createPurchaseRequest({supplierId:'S1',currency:'CNY',totalAmount:200,lines:[{sku:'A',quantity:1,unit:'件',unitPrice:200}]},'u1'); pr=await f.service.transitionPurchaseRequest(pr.id,'submitted',{expectedVersion:1,actor:'u1'}); pr=await f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:2,actor:'m1'}); await assert.rejects(()=>f.service.recordPathDecision(pr.id,{path:'direct_po',expectedVersion:3},'m1'),e=>e.code==='RFQ_REQUIRED_BY_POLICY'); const decided=await f.service.recordPathDecision(pr.id,{path:'direct_po',expectedVersion:3,overrideReason:'生产停线风险'},'m1'); assert.equal(decided.procurementPathDecision.policySnapshot.amount,200); await rm(f.dir,{recursive:true,force:true}) })
test('approved PR creates one idempotent canonical RFQ and locks direct PO',async()=>{const f=await fixture();let pr=await f.service.createPurchaseRequest({currency:'CNY',totalAmount:20,lines:[{sku:'A',quantity:1,unit:'件',unitPrice:20}]},'u');pr=await f.service.transitionPurchaseRequest(pr.id,'submitted',{expectedVersion:1,actor:'u'});pr=await f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:2,actor:'m'});const one=await f.service.createRfqFromPurchaseRequest(pr.id,{expectedVersion:3},'buyer');const two=await f.service.createRfqFromPurchaseRequest(pr.id,{expectedVersion:3},'buyer');assert.equal(one.rfq.id,two.rfq.id);assert.equal((await f.repo.list('rfq')).length,1);await assert.rejects(()=>f.service.createDirectPoFromPurchaseRequest(pr.id,{expectedVersion:4},'buyer'),e=>e.code==='DOWNSTREAM_OBJECT_ALREADY_EXISTS');await rm(f.dir,{recursive:true,force:true})})
test('direct PO creation is atomic, idempotent and converts PR only after success',async()=>{const f=await fixture({rfqRequiredAboveAmount:1000});let pr=await f.service.createPurchaseRequest({supplierId:'S1',currency:'CNY',paymentTermsId:'NET30',expectedDeliveryDate:'2026-08-01',totalAmount:20,lines:[{sku:'A',quantity:1,unit:'件',unitPrice:20}]},'u');pr=await f.service.transitionPurchaseRequest(pr.id,'submitted',{expectedVersion:1,actor:'u'});pr=await f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:2,actor:'m'});const one=await f.service.createDirectPoFromPurchaseRequest(pr.id,{expectedVersion:3},'buyer');const two=await f.service.createDirectPoFromPurchaseRequest(pr.id,{expectedVersion:3},'buyer');assert.equal(one.purchaseOrder.id,two.purchaseOrder.id);assert.equal(one.purchaseRequest.status,'converted');assert.equal((await f.repo.list('po')).length,1);await rm(f.dir,{recursive:true,force:true})})
test('permission callback blocks viewer writes and non-manager approval',async()=>{const dir=await mkdtemp(join(tmpdir(),'flowchain-perm-'));const repo=createDurableProcurementRepository({dataFile:join(dir,'p.json')});const denied=createProcurementWorkflowService({repository:repo,permission:async()=>false});await assert.rejects(()=>denied.createPurchaseRequest({},'viewer'),e=>e.code==='PERMISSION_DENIED');const service=createProcurementWorkflowService({repository:repo,permission:async(_actor,action)=>action!=='pr.approve'});let pr=await service.createPurchaseRequest({},'specialist');pr=await service.transitionPurchaseRequest(pr.id,'submitted',{expectedVersion:1,actor:'specialist'});await assert.rejects(()=>service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:2,actor:'specialist'}),e=>e.code==='PERMISSION_DENIED');await rm(dir,{recursive:true,force:true})})
