import test from 'node:test'
import assert from 'node:assert/strict'
import { access, mkdtemp, readFile, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { createDurableProcurementRepository } from '../repositories/durable-procurement-repository.mjs'
import { createProcurementWorkflowService } from '../services/procurement-workflow-service.mjs'

const line = (patch = {}) => ({ lineId: crypto.randomUUID(), sourceType:'non_catalog_item', lineBasis:'quantity', supplierId:'SUP-1', itemNameSnapshot:'物料', unitSnapshot:'件', commodityId:'general', quantity:1, estimatedUnitPrice:20, needByDate:'2026-08-01', targetWarehouseId:'WH-1', currency:'CNY', ...patch })
async function fixture() { const dir=await mkdtemp(join(tmpdir(),'flowchain-proc-')); const file=join(dir,'transactions.json'); const repository=createDurableProcurementRepository({dataFile:file}); return {dir,file,repository,service:createProcurementWorkflowService({repository})} }

test('read-only empty procurement runtime does not create a workspace file', async()=>{ const f=await fixture(); try { assert.deepEqual(await f.repository.list('pr'),[]); await assert.rejects(()=>access(f.file),error=>error.code==='ENOENT') } finally { await rm(f.dir,{recursive:true,force:true}) } })
test('runtime v2 is initialized empty and survives repository restart', async()=>{ const f=await fixture(); try { const pr=await f.service.createPurchaseRequest({requesterId:'forged',departmentId:'operations',lines:[line()]},'authenticated-user'); assert.equal(pr.requesterId,'authenticated-user'); const stored=JSON.parse(await readFile(f.file,'utf8')); assert.equal(stored.schemaVersion,2); assert.equal(stored.initialized,true); const restarted=createDurableProcurementRepository({dataFile:f.file}); assert.equal((await restarted.get('pr',pr.id)).id,pr.id) } finally { await rm(f.dir,{recursive:true,force:true}) } })
test('supplier and explicit price are mandatory even for drafts', async()=>{ const f=await fixture(); try { await assert.rejects(()=>f.service.createPurchaseRequest({lines:[line({supplierId:''})]},'u'),e=>e.code==='SUPPLIER_REQUIRED'); await assert.rejects(()=>f.service.createPurchaseRequest({lines:[line({estimatedUnitPrice:null})]},'u'),e=>e.code==='LINE_VALUE_REQUIRED') } finally { await rm(f.dir,{recursive:true,force:true}) } })
test('PR transition checks version and reject reason is handled by route boundary', async()=>{ const f=await fixture(); try { let pr=await f.service.createPurchaseRequest({lines:[line()]},'u'); await assert.rejects(()=>f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:1,actor:'m'}),e=>e.code==='INVALID_STATE_TRANSITION'); pr=await f.service.transitionPurchaseRequest(pr.id,'submitted',{expectedVersion:1,actor:'u'}); await assert.rejects(()=>f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:1,actor:'m'}),e=>e.code==='VERSION_CONFLICT'); assert.equal((await f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:2,actor:'m'})).status,'approved') } finally { await rm(f.dir,{recursive:true,force:true}) } })
test('approved multi-supplier PR splits idempotent draft not-sent POs', async()=>{ const f=await fixture(); try { let pr=await f.service.createPurchaseRequest({lines:[line(),line({lineId:crypto.randomUUID(),supplierId:'SUP-2'}),line({lineId:crypto.randomUUID(),quantity:2})]},'u'); pr=await f.service.transitionPurchaseRequest(pr.id,'submitted',{expectedVersion:1,actor:'u'}); pr=await f.service.transitionPurchaseRequest(pr.id,'approved',{expectedVersion:2,actor:'m'}); const first=await f.service.createDirectPoFromPurchaseRequest(pr.id,{expectedVersion:3},'buyer'); const replay=await f.service.createDirectPoFromPurchaseRequest(pr.id,{expectedVersion:3},'buyer'); assert.equal(first.createdPurchaseOrders.length,2); assert.equal(replay.createdPurchaseOrders.length,2); assert.equal((await f.repository.list('po')).length,2); assert.ok(first.createdPurchaseOrders.every(po=>po.status==='draft'&&po.transmissionStatus==='not_sent')); assert.equal(first.createdPurchaseOrders.find(po=>po.supplierId==='SUP-1').lines.length,2) } finally { await rm(f.dir,{recursive:true,force:true}) } })
