import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { createDurableSupplierRepository } from '../repositories/durable-supplier-repository.mjs'
import { handleMasterDataRoute } from '../routes/master-data.routes.mjs'
import { createDurableProcurementRepository } from '../repositories/durable-procurement-repository.mjs'
import { createProcurementWorkflowService } from '../services/procurement-workflow-service.mjs'

async function fixture(){const dir=await mkdtemp(join(tmpdir(),'flowchain-supplier-'));const file=join(dir,'suppliers.json');return{dir,file,repo:createDurableSupplierRepository({dataFile:file})}}
const supplier=(code='SUP-A',patch={})=>({supplierCode:code,supplierName:`供应商 ${code}`,status:'active',email:`${code.toLowerCase()}@example.com`,deliveryCycleDays:7,defaultCurrency:'CNY',paymentTermsId:'NET30',bankAccountNumber:'6222000012345678',...patch})
test('supplier create update and repository restart persist',async()=>{const f=await fixture();try{const row=await f.repo.createSupplier(supplier(),'admin');assert.equal((await f.repo.getSupplier(row.id)).supplierName,'供应商 SUP-A');await f.repo.updateSupplier(row.id,{supplierName:'更新供应商',expectedVersion:1},'admin');const restarted=createDurableSupplierRepository({dataFile:f.file});assert.equal((await restarted.getSupplier(row.id)).supplierName,'更新供应商')}finally{await rm(f.dir,{recursive:true,force:true})}})
test('supplier unique fields email and optimistic version are enforced',async()=>{const f=await fixture();try{const row=await f.repo.createSupplier(supplier('SUP-A',{creditCode:'CREDIT-1'}),'admin');await assert.rejects(()=>f.repo.createSupplier(supplier('SUP-A'),'admin'),e=>e.code==='SUPPLIER_CODE_DUPLICATE');await assert.rejects(()=>f.repo.createSupplier(supplier('SUP-B',{creditCode:'CREDIT-1'}),'admin'),e=>e.code==='CREDIT_CODE_DUPLICATE');await assert.rejects(()=>f.repo.createSupplier(supplier('SUP-C',{email:'bad'}),'admin'),e=>e.code==='SUPPLIER_EMAIL_INVALID');await assert.rejects(()=>f.repo.updateSupplier(row.id,{supplierName:'x',expectedVersion:9},'admin'),e=>e.code==='VERSION_CONFLICT')}finally{await rm(f.dir,{recursive:true,force:true})}})
test('standard read masks bank account and selector omits sensitive fields',async()=>{const f=await fixture();try{const row=await f.repo.createSupplier(supplier(),'admin');assert.equal((await f.repo.getSupplier(row.id)).bankAccountNumber,'****5678');const selected=(await f.repo.selectSuppliers())[0];assert.equal(selected.supplierCode,'SUP-A');assert.equal('bankAccountNumber'in selected,false);assert.equal('taxIdentificationNumber'in selected,false)}finally{await rm(f.dir,{recursive:true,force:true})}})
test('empty initialized supplier runtime stays empty without fallback',async()=>{const f=await fixture();try{assert.deepEqual(await f.repo.listSuppliers(),[]);assert.equal((await f.repo.snapshot()).initialized,true)}finally{await rm(f.dir,{recursive:true,force:true})}})
test('relationships share one repository, enforce active supplier, and one preferred per item',async()=>{const f=await fixture();try{const a=await f.repo.createSupplier(supplier('SUP-A'),'admin'),b=await f.repo.createSupplier(supplier('SUP-B'),'admin');const item={itemId:'ITEM-1',status:'active',purchaseUnit:'件'};const ra=await f.repo.createItemSupplier(item.itemId,{supplierId:a.id,preferred:true},'admin',item);const rb=await f.repo.createItemSupplier(item.itemId,{supplierId:b.id,preferred:true},'admin',item);const rows=await f.repo.listItemSuppliers(item.itemId);assert.equal(rows.filter(r=>r.preferred).length,1);assert.equal(rows.find(r=>r.relationshipId===rb.relationshipId).preferred,true);await f.repo.updateSupplier(a.id,{status:'inactive',expectedVersion:1},'admin');await assert.rejects(()=>f.repo.createItemSupplier('ITEM-2',{supplierId:a.id},'admin',{itemId:'ITEM-2',status:'active'}),e=>e.code==='SUPPLIER_INACTIVE');assert.equal((await f.repo.approvedSuppliersForItem(item.itemId)).length,1);assert.equal(ra.itemId,item.itemId)}finally{await rm(f.dir,{recursive:true,force:true})}})

function route(repository,{method='GET',path='/api/master-data/suppliers',role='manager',body}={}){let response;return{ctx:{req:{method,headers:{'x-flowchain-role':role,'x-flowchain-user':'route-user'}},res:{},url:new URL(path,'http://localhost'),repositories:{masterData:repository},readBody:async()=>body,send(_res,status,payload){response={status,payload}}},get response(){return response}}}

test('supplier API create patch and masked detail use durable repository',async()=>{const f=await fixture();try{const create=route(f.repo,{method:'POST',body:supplier('SUP-API')});assert.equal(await handleMasterDataRoute(create.ctx),true);assert.equal(create.response.status,201);const created=create.response.payload.supplier;const patch=route(f.repo,{method:'PATCH',path:`/api/master-data/suppliers/${created.id}`,body:{supplierName:'API Updated',expectedVersion:1}});await handleMasterDataRoute(patch.ctx);assert.equal(patch.response.status,200);const detail=route(f.repo,{path:`/api/master-data/suppliers/${created.id}`});await handleMasterDataRoute(detail.ctx);assert.equal(detail.response.payload.supplier.supplierName,'API Updated');assert.equal(detail.response.payload.supplier.bankAccountNumber,'****5678')}finally{await rm(f.dir,{recursive:true,force:true})}})

test('viewer cannot create or patch suppliers',async()=>{const f=await fixture();try{const deniedCreate=route(f.repo,{method:'POST',role:'viewer',body:supplier('SUP-VIEW')});await handleMasterDataRoute(deniedCreate.ctx);assert.equal(deniedCreate.response.status,403);const created=await f.repo.createSupplier(supplier('SUP-ADMIN'),'admin');const deniedPatch=route(f.repo,{method:'PATCH',path:`/api/master-data/suppliers/${created.id}`,role:'viewer',body:{status:'inactive',expectedVersion:1}});await handleMasterDataRoute(deniedPatch.ctx);assert.equal(deniedPatch.response.status,403);assert.equal((await f.repo.getSupplier(created.id)).status,'active')}finally{await rm(f.dir,{recursive:true,force:true})}})

test('relationship duplicates and reactivation for inactive supplier are rejected',async()=>{const f=await fixture();try{const item={itemId:'ITEM-REL',status:'active',purchaseUnit:'件'};const created=await f.repo.createSupplier(supplier('SUP-REL'),'admin');const relationship=await f.repo.createItemSupplier(item.itemId,{supplierId:created.id,active:true,approved:true},'admin',item);await assert.rejects(()=>f.repo.createItemSupplier(item.itemId,{supplierId:created.id},'admin',item),error=>error.code==='RELATIONSHIP_DUPLICATE');await f.repo.updateItemSupplier(item.itemId,relationship.relationshipId,{active:false,expectedVersion:1},'admin',item);await f.repo.updateSupplier(created.id,{status:'inactive',expectedVersion:1},'admin');await assert.rejects(()=>f.repo.updateItemSupplier(item.itemId,relationship.relationshipId,{active:true,expectedVersion:2},'admin',item),error=>error.code==='SUPPLIER_INACTIVE');assert.equal((await f.repo.selectSuppliers()).length,0)}finally{await rm(f.dir,{recursive:true,force:true})}})

test('historical procurement keeps supplier snapshot after supplier is inactive',async()=>{const f=await fixture();try{const created=await f.repo.createSupplier(supplier('SUP-HISTORY'),'admin');const procurement=createDurableProcurementRepository({dataFile:join(f.dir,'procurement.json')});const service=createProcurementWorkflowService({repository:procurement,itemRepository:{getSupplier:(id)=>f.repo.getSupplier(id)}});const pr=await service.createPurchaseRequest({lines:[{sourceType:'non_catalog_item',lineBasis:'amount',supplierId:created.id,itemNameSnapshot:'历史服务',estimatedAmount:100,currency:'CNY',targetWarehouseId:'WH-1',needByDate:'2026-08-01'}]},'buyer');await f.repo.updateSupplier(created.id,{status:'inactive',expectedVersion:1},'admin');const stored=await procurement.get('pr',pr.id);assert.equal(stored.lines[0].supplierSnapshot.supplierName,'供应商 SUP-HISTORY');assert.equal((await f.repo.selectSuppliers()).some(row=>row.id===created.id),false)}finally{await rm(f.dir,{recursive:true,force:true})}})
