import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { createDurableSupplierRepository } from '../repositories/durable-supplier-repository.mjs'

async function fixture(){const dir=await mkdtemp(join(tmpdir(),'flowchain-supplier-'));const file=join(dir,'suppliers.json');return{dir,file,repo:createDurableSupplierRepository({dataFile:file})}}
const supplier=(code='SUP-A',patch={})=>({supplierCode:code,supplierName:`供应商 ${code}`,status:'active',email:`${code.toLowerCase()}@example.com`,deliveryCycleDays:7,defaultCurrency:'CNY',paymentTermsId:'NET30',bankAccountNumber:'6222000012345678',...patch})
test('supplier create update and repository restart persist',async()=>{const f=await fixture();try{const row=await f.repo.createSupplier(supplier(),'admin');assert.equal((await f.repo.getSupplier(row.id)).supplierName,'供应商 SUP-A');await f.repo.updateSupplier(row.id,{supplierName:'更新供应商',expectedVersion:1},'admin');const restarted=createDurableSupplierRepository({dataFile:f.file});assert.equal((await restarted.getSupplier(row.id)).supplierName,'更新供应商')}finally{await rm(f.dir,{recursive:true,force:true})}})
test('supplier unique fields email and optimistic version are enforced',async()=>{const f=await fixture();try{const row=await f.repo.createSupplier(supplier('SUP-A',{creditCode:'CREDIT-1'}),'admin');await assert.rejects(()=>f.repo.createSupplier(supplier('SUP-A'),'admin'),e=>e.code==='SUPPLIER_CODE_DUPLICATE');await assert.rejects(()=>f.repo.createSupplier(supplier('SUP-B',{creditCode:'CREDIT-1'}),'admin'),e=>e.code==='CREDIT_CODE_DUPLICATE');await assert.rejects(()=>f.repo.createSupplier(supplier('SUP-C',{email:'bad'}),'admin'),e=>e.code==='SUPPLIER_EMAIL_INVALID');await assert.rejects(()=>f.repo.updateSupplier(row.id,{supplierName:'x',expectedVersion:9},'admin'),e=>e.code==='VERSION_CONFLICT')}finally{await rm(f.dir,{recursive:true,force:true})}})
test('standard read masks bank account and selector omits sensitive fields',async()=>{const f=await fixture();try{const row=await f.repo.createSupplier(supplier(),'admin');assert.equal((await f.repo.getSupplier(row.id)).bankAccountNumber,'****5678');const selected=(await f.repo.selectSuppliers())[0];assert.equal(selected.supplierCode,'SUP-A');assert.equal('bankAccountNumber'in selected,false);assert.equal('taxIdentificationNumber'in selected,false)}finally{await rm(f.dir,{recursive:true,force:true})}})
test('empty initialized supplier runtime stays empty without fallback',async()=>{const f=await fixture();try{assert.deepEqual(await f.repo.listSuppliers(),[]);assert.equal((await f.repo.snapshot()).initialized,true)}finally{await rm(f.dir,{recursive:true,force:true})}})
test('relationships share one repository, enforce active supplier, and one preferred per item',async()=>{const f=await fixture();try{const a=await f.repo.createSupplier(supplier('SUP-A'),'admin'),b=await f.repo.createSupplier(supplier('SUP-B'),'admin');const item={itemId:'ITEM-1',status:'active',purchaseUnit:'件'};const ra=await f.repo.createItemSupplier(item.itemId,{supplierId:a.id,preferred:true},'admin',item);const rb=await f.repo.createItemSupplier(item.itemId,{supplierId:b.id,preferred:true},'admin',item);const rows=await f.repo.listItemSuppliers(item.itemId);assert.equal(rows.filter(r=>r.preferred).length,1);assert.equal(rows.find(r=>r.relationshipId===rb.relationshipId).preferred,true);await f.repo.updateSupplier(a.id,{status:'inactive',expectedVersion:1},'admin');await assert.rejects(()=>f.repo.createItemSupplier('ITEM-2',{supplierId:a.id},'admin',{itemId:'ITEM-2',status:'active'}),e=>e.code==='SUPPLIER_INACTIVE');assert.equal((await f.repo.approvedSuppliersForItem(item.itemId)).length,1);assert.equal(ra.itemId,item.itemId)}finally{await rm(f.dir,{recursive:true,force:true})}})
