// @ts-nocheck
import { useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import { A, Card } from "../../components/ui";
import PurchasingRequests from "../purchase-requests/Page";
import type { PurchaseIntent } from "../../types/scm";
import type { ActiveContext } from "../ai-assistant/Panel";

type PurTab="workbench"|"overview"|"requests"|"rfq"|"orders"|"contracts"|"receiving"|"receiving-new"|"receiving-edit"|"invoices"|"match"|"returns";
type Focus={entityType:string;entityId:string;at:number}|null;
type PR={id:string;status:string;totalAmount:number;updatedAt:string;lines:Array<{supplierId:string}>};
type PO={id:string;status:string;transmissionStatus:string;totalAmount:number;supplierId:string;targetWarehouseId:string;sourcePrId:string;sourcePurchaseRequestId:string;lines:Array<{sourcePurchaseRequestLineId:string;itemNameSnapshot:string;estimatedAmount:number}>;updatedAt:string};
const fetchJson=async<T,>(url:string)=>{const response=await fetch(url);if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return response.json() as Promise<T>};

export default function ProcurementPanel({intent=null,view,focus,onNavigate,onActiveContextChange}:{intent?:PurchaseIntent|null;view?:PurTab;focus?:Focus;onOpenRfq?:()=>void;onNavigate?:(moduleId:string,focus?:unknown)=>void;onActiveContextChange?:(context:ActiveContext|null)=>void}){
  if(!view||view==="workbench"||view==="overview")return <RuntimeWorkbench onNavigate={onNavigate}/>;
  if(view==="requests")return <PurchasingRequests intent={intent} focus={focus} onNavigate={onNavigate} onActiveContextChange={onActiveContextChange}/>;
  if(view==="orders")return <RuntimeOrders focus={focus} onNavigate={onNavigate}/>;
  const empty:{[key:string]:[string,string]}={rfq:["暂无询价单","采购申请需要询价时，记录将显示在这里。"],receiving:["暂无采购收货记录","采购订单收货后，记录将显示在这里。"],invoices:["暂无供应商发票","供应商发票录入后，记录将显示在这里。"],match:["暂无匹配记录","收货与发票数据完整后可进行三单匹配。"],returns:["暂无采购退货记录","采购退货发生后，记录将显示在这里。"],contracts:["暂无采购合同","当前未接通合同 runtime repository。"]};const copy=empty[view]||["当前视图暂无数据",""];
  return <Card className="py-16 text-center"><h1 className="text-base font-semibold">{copy[0]}</h1><p className="mt-2 text-xs" style={{color:A.sub}}>{copy[1]}</p></Card>;
}

function RuntimeWorkbench({onNavigate}:{onNavigate?:(moduleId:string,focus?:unknown)=>void}){const[prs,setPrs]=useState<PR[]>([]),[pos,setPos]=useState<PO[]>([]),[state,setState]=useState<"loading"|"loaded"|"error">("loading"),[filter,setFilter]=useState<"all"|"approval"|"overdue"|"tracking">("all");const load=async()=>{setState("loading");try{const[p,o]=await Promise.all([fetchJson<PR[]>("/api/procurement/requests"),fetchJson<PO[]>("/api/procurement/orders")]);setPrs(p);setPos(o);setState("loaded")}catch{setState("error")}};useEffect(()=>{load()},[]);const rows=[...prs.filter(p=>["submitted","approved"].includes(p.status)).map(p=>({id:p.id,type:"采购申请",status:p.status,amount:p.totalAmount,bucket:p.status==="submitted"?"approval":"tracking",route:"procurement:requests",entityType:"purchase_request"})),...pos.filter(p=>p.status==="draft").map(p=>({id:p.id,type:"采购订单",status:`${p.status} · ${p.transmissionStatus}`,amount:p.totalAmount,bucket:"tracking",route:"procurement:orders",entityType:"purchase_order"}))],shown=rows.filter(r=>filter==="all"||r.bucket===filter),approval=rows.filter(r=>r.bucket==="approval").length,tracking=rows.filter(r=>r.bucket==="tracking").length;
  if(state==="error")return <Card className="p-12 text-center"><div>采购工作台加载失败</div><button onClick={load} className="mt-3 text-blue-600">重试</button></Card>;
  return <div className="space-y-4"><Card className="p-5"><div className="flex items-center justify-between"><div><h1 className="text-lg font-semibold">今日采购待办：{rows.length}</h1><p className="text-xs" style={{color:A.sub}}>采购申请、审批与 Draft PO 来自采购 runtime repository。</p></div><div className="flex gap-2"><button onClick={load} className="inline-flex items-center gap-1 rounded border px-3 py-2 text-xs"><RefreshCw size={14}/>刷新</button><button onClick={()=>onNavigate?.("procurement:requests")} className="rounded bg-blue-600 px-3 py-2 text-xs text-white">新建采购申请</button></div></div></Card><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[{id:"all" as const,label:"全部待办",value:rows.length},{id:"approval" as const,label:"待我审批",value:approval},{id:"overdue" as const,label:"逾期处理",value:0},{id:"tracking" as const,label:"跟进中",value:tracking}].map(x=><button key={x.id} onClick={()=>setFilter(x.id)} className="rounded border bg-white p-4 text-left"><div className="text-xs">{x.label}</div><div className="text-2xl font-semibold">{x.value}</div></button>)}</div><Card className="overflow-hidden"><div className="border-b p-4 text-sm font-semibold">待办队列</div>{state==="loading"?<div className="py-12 text-center text-xs">加载中</div>:shown.length===0?<div className="py-12 text-center text-sm" style={{color:A.sub}}>暂无采购事项<br/><span className="text-xs">点击“新建采购申请”开始录入。</span></div>:<table className="w-full text-xs"><tbody>{shown.map(r=><tr key={r.id} className="cursor-pointer border-t" onClick={()=>onNavigate?.(r.route,{entityType:r.entityType,entityId:r.id})}><td className="p-3">{r.type}</td><td className="p-3 text-blue-600 underline">{r.id}</td><td className="p-3">{r.status}</td><td className="p-3">{r.amount}</td></tr>)}</tbody></table>}</Card></div>}

function RuntimeOrders({focus,onNavigate}:{focus?:Focus;onNavigate?:(moduleId:string,focus?:unknown)=>void}){const[rows,setRows]=useState<PO[]>([]),[error,setError]=useState("");const load=()=>fetchJson<PO[]>("/api/procurement/orders").then(setRows).catch(e=>setError(e.message));useEffect(load,[]);const selected=focus?.entityType==="purchase_order"?rows.find(row=>row.id===focus.entityId):null;if(error)return <Card className="p-12 text-center">采购订单加载失败<button onClick={load}>重试</button></Card>;if(selected)return <div className="space-y-4"><button onClick={()=>onNavigate?.("procurement:orders")}>返回采购订单列表</button><Card className="p-5"><h1 className="text-lg font-semibold">{selected.id}</h1><p className="mt-1 text-xs" style={{color:A.sub}}>{selected.status} · {selected.transmissionStatus} · {selected.supplierId}</p><div className="mt-4 text-sm">金额：{selected.totalAmount} · 目标仓库：{selected.targetWarehouseId}</div><h2 className="mt-5 text-sm font-semibold">来源采购申请</h2><button onClick={()=>onNavigate?.("procurement:requests",{entityType:"purchase_request",entityId:selected.sourcePrId||selected.sourcePurchaseRequestId})} className="mt-2 text-sm text-blue-600 underline">{selected.sourcePrId||selected.sourcePurchaseRequestId}</button><h2 className="mt-5 text-sm font-semibold">采购行</h2>{selected.lines.map(line=><div key={line.sourcePurchaseRequestLineId} className="border-t py-2 text-xs">{line.itemNameSnapshot} · {line.estimatedAmount} · 来源行 {line.sourcePurchaseRequestLineId}</div>)}</Card></div>;return <div className="space-y-4"><h1 className="text-lg font-semibold">采购订单</h1>{rows.length===0?<Card className="py-14 text-center text-sm" style={{color:A.sub}}>暂无采购订单<br/><span className="text-xs">审批通过并转换后，Draft PO 将显示在这里。</span></Card>:<Card className="overflow-hidden"><table className="w-full text-xs"><thead><tr>{["采购订单","Supplier","状态","发送状态","金额","来源 PR"].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="p-3"><button onClick={()=>onNavigate?.("procurement:orders",{entityType:"purchase_order",entityId:row.id})} className="text-blue-600 underline">{row.id}</button></td><td className="p-3">{row.supplierId}</td><td className="p-3">{row.status}</td><td className="p-3">{row.transmissionStatus}</td><td className="p-3">{row.totalAmount}</td><td className="p-3"><button onClick={()=>onNavigate?.("procurement:requests",{entityType:"purchase_request",entityId:row.sourcePrId})} className="text-blue-600 underline">{row.sourcePrId}</button></td></tr>)}</tbody></table></Card>}</div>}
