import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Printer, Search } from "lucide-react";
import { A, Card, Chip, KpiCard, Modal, SectionHeader } from "../../components/ui";
import { useListRouteState } from "../../components/navigation/useListRouteState";
import PrintLayoutEditor from "../print-layout/PrintLayoutEditor";
import { adaptSignReceipt } from "../print-layout/printDataAdapters";
import { SIGN_RECEIPTS } from "./receiptData";
import type { SignReceipt, SignReceiptStatus } from "./receiptTypes";
import { useNavigate } from "react-router";
import { BusinessEntityLink } from "../../components/business/BusinessEntityLink";

const statuses: Array<"全部" | SignReceiptStatus> = ["全部", "待签收", "正常签收", "部分签收", "异常签收"];
const color = (status: SignReceiptStatus) => status === "正常签收" ? A.green : status === "待签收" ? A.blue : status === "部分签收" ? A.orange : A.red;
const receiptListDefaults = { q: "", status: "全部", page: "1", sort: "signDate-desc" };

export default function ReceiptPage() {
  const navigate = useNavigate();
  const { values, setValue, selectedId, setSelectedId } = useListRouteState({ moduleId: "sales", routeId: "sales:receipts", defaults: receiptListDefaults });
  const { q: search, status } = values;
  const selected = SIGN_RECEIPTS.find((item) => item.id === selectedId) || null;
  const [printing, setPrinting] = useState<SignReceipt | null>(null);
  const rows = useMemo(() => SIGN_RECEIPTS.filter((item) => (!search.trim() || [item.receiptNo, item.deliveryNo, item.salesOrderNo, item.customerName, item.receiverName].some((value) => value.toLowerCase().includes(search.trim().toLowerCase()))) && (status === "全部" || item.status === status)), [search, status]);
  const exceptionQty = (item: SignReceipt) => item.lines.reduce((sum, line) => sum + Math.max(0, line.shippedQty - line.receivedQty) + line.damagedQty, 0);
  return <div className="space-y-4" data-testid="receipt-page">
    <div className="flex justify-end"><button className="fc-action-button fc-action-primary" onClick={() => navigate("/app/sales/receipts/new")}>新建签收单</button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><KpiCard label="待签收" value={String(SIGN_RECEIPTS.filter((item) => item.status === "待签收").length)} icon={ClipboardCheck} color={A.blue} /><KpiCard label="正常签收" value={String(SIGN_RECEIPTS.filter((item) => item.status === "正常签收").length)} icon={CheckCircle2} color={A.green} /><KpiCard label="部分签收" value={String(SIGN_RECEIPTS.filter((item) => item.status === "部分签收").length)} icon={ClipboardCheck} color={A.orange} /><KpiCard label="异常签收" value={String(SIGN_RECEIPTS.filter((item) => item.status === "异常签收").length)} icon={AlertTriangle} color={A.red} /></div>
    <Card><div className="p-4 flex items-center gap-2" style={{ borderBottom: `1px solid ${A.border}` }}><div className="h-9 px-3 rounded-lg flex items-center gap-2 min-w-[300px]" style={{ background: A.gray6 }}><Search size={13} /><input aria-label="搜索签收单" className="w-full bg-transparent outline-none fc-body" placeholder="搜索签收单号、发货单号、客户" value={search} onChange={(event) => setValue("q", event.target.value)} /></div><select aria-label="签收状态" className="h-9 rounded-lg px-3 fc-body" style={{ border: `1px solid ${A.border}` }} value={status} onChange={(event) => setValue("status", event.target.value)}>{statuses.map((item) => <option key={item}>{item}</option>)}</select><span className="ml-auto fc-caption" style={{ color: A.gray2 }}>{rows.length} 张签收单</span></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-xs"><thead><tr>{["签收单号", "发货单号", "销售订单号", "客户", "签收人", "签收日期", "签收状态", "异常数量", "操作"].map((item) => <th key={item} className="px-3 py-3 text-left" style={{ color: A.gray1 }}>{item}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.id} data-testid={`receipt-row-${item.receiptNo}`} style={{ borderTop: `1px solid ${A.border}` }}><td className="px-3 py-3 font-semibold"><BusinessEntityLink entityType="sign_receipt" entityId={item.receiptNo}>{item.receiptNo}</BusinessEntityLink></td><td className="px-3 py-3"><BusinessEntityLink entityType="delivery_note" entityId={item.deliveryNo}>{item.deliveryNo}</BusinessEntityLink></td><td className="px-3 py-3"><BusinessEntityLink entityType="sales_order" entityId={item.salesOrderNo}>{item.salesOrderNo}</BusinessEntityLink></td><td className="px-3 py-3 font-medium">{item.customerName}</td><td className="px-3 py-3">{item.receiverName}</td><td className="px-3 py-3">{item.signDate}</td><td className="px-3 py-3"><Chip label={item.status} color={color(item.status)} bg={`${color(item.status)}16`} /></td><td className="px-3 py-3" style={{ color: exceptionQty(item) ? A.red : A.green }}>{exceptionQty(item)}</td><td className="px-3 py-3"><div className="flex gap-2"><button onClick={() => setSelectedId(item.id)} className="px-2.5 py-1.5 rounded-md" style={{ background: A.gray6, color: A.blue }}>快速预览</button><button aria-label={`打印签收单 ${item.receiptNo}`} onClick={() => setPrinting(item)} className="px-2.5 py-1.5 rounded-md flex items-center gap-1" style={{ background: "#f0f6ff", color: A.blue }}><Printer size={12} />打印</button></div></td></tr>)}</tbody></table></div>
    </Card>
    <Modal open={Boolean(selected)} onClose={() => setSelectedId("")} title="签收单详情" subtitle={selected?.receiptNo} width={1040} footer={selected && <button onClick={() => setPrinting(selected)} className="px-3 py-2 rounded-lg text-xs text-white flex items-center gap-1" style={{ background: A.blue }}><Printer size={13} />打印签收单</button>}>
      {selected && <div className="space-y-5"><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["签收单号", selected.receiptNo], ["签收状态", selected.status], ["客户", selected.customerName], ["签收人", selected.receiverName], ["签收电话", selected.receiverPhone || "—"], ["签收日期", selected.signDate], ["签收地点", selected.signLocation || "—"], ["配送人", selected.deliveryPerson || "—"], ["发货单号", selected.deliveryNo], ["销售订单", selected.salesOrderNo], ["审核人", selected.reviewedBy || "待审核"], ["签名信息", selected.signature || "待签名"]].map(([label, value]) => <div key={label} className="p-3 rounded-lg" style={{ background: A.gray6 }}><div className="fc-caption" style={{ color: A.gray2 }}>{label}</div><div className="text-xs font-semibold mt-1">{value}</div></div>)}</div>
        <div><SectionHeader title="收货差异与明细" /><div className="overflow-x-auto rounded-xl border" style={{ borderColor: A.border }}><table className="w-full text-xs"><thead><tr>{["SKU", "商品名称", "发货数量", "实收数量", "损坏数量", "差异", "单位", "备注"].map((item) => <th key={item} className="px-3 py-2 text-left" style={{ color: A.gray1 }}>{item}</th>)}</tr></thead><tbody>{selected.lines.map((line) => <tr key={line.sku} style={{ borderTop: `1px solid ${A.border}` }}><td className="px-3 py-2" style={{ color: A.blue }}>{line.sku}</td><td className="px-3 py-2 font-medium">{line.itemName}</td><td className="px-3 py-2">{line.shippedQty}</td><td className="px-3 py-2">{line.receivedQty}</td><td className="px-3 py-2" style={{ color: line.damagedQty ? A.red : A.label }}>{line.damagedQty}</td><td className="px-3 py-2">{line.shippedQty - line.receivedQty}</td><td className="px-3 py-2">{line.unit}</td><td className="px-3 py-2">{line.remarks || "—"}</td></tr>)}</tbody></table></div></div>
        <Card className="p-4"><SectionHeader title="异常说明" /><div className="text-xs leading-5" style={{ color: selected.exceptionNote ? A.red : A.sub }}>{selected.exceptionNote || "无签收异常。"}</div></Card>
      </div>}
    </Modal>
    {printing && <PrintLayoutEditor open documentType="sign_receipt" documentNo={printing.receiptNo} data={adaptSignReceipt(printing)} onClose={() => setPrinting(null)} />}
  </div>;
}
