import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router";
import { AlertTriangle, ArrowLeft, Check, ClipboardCheck, CloudOff, PackageCheck, RefreshCw, Send, Wifi } from "lucide-react";
import { apiJson } from "../../lib/api-client";
import { useI18n } from "../../i18n/I18n";

type Task = { taskId: string; taskType: string; entityId: string; title: string; summary?: string | null; status: string; amountSummary?: { amount?: string; currency?: string } | null; availableActions: string[]; entityVersion: number; deepLink: string; limitations?: string[]; updatedAt: string };
type Po = { id: string; orderNumber: string; status: string; supplierSnapshot?: { supplierName?: string } | null; lines: Array<{ id?: string; sku?: string; itemNameSnapshot?: string; quantity?: number; unitSnapshot?: string; unitPrice?: number | null; amount?: number | null }>; amountSummary?: { totalAmount?: number; currency?: string } | null; entityVersion: number; availableActions: string[]; limitations: string[] };
type ReceivingPo = { id: string; status: string; supplierName?: string | null; currency: string; lines: Array<{ id: string; sku?: string; itemName?: string; orderedQuantity: string; receivedQuantity: string; remainingQuantity: string; unit?: string }> };
type Warehouse = { id: string; code: string; name: string };

const button = "inline-flex min-h-11 items-center justify-center gap-2 rounded-md px-4 py-2 text-sm font-medium disabled:cursor-not-allowed disabled:opacity-50";
const secondary = `${button} border border-slate-300 bg-white text-slate-800 hover:bg-slate-50`;
const primary = `${button} bg-blue-700 text-white hover:bg-blue-800`;
const danger = `${button} border border-rose-300 bg-white text-rose-700 hover:bg-rose-50`;
const mutationId = () => crypto.randomUUID();

function StatusBar({ online, pending, conflict, tr }: { online: boolean; pending: boolean; conflict: string; tr: (zh: string, en: string) => string }) {
  return <div className="flex min-h-11 flex-wrap items-center gap-3 border-b border-slate-200 bg-white px-4 py-2 text-sm" data-testid="mobile-network-status">
    <span className={`inline-flex items-center gap-2 font-medium ${online ? "text-emerald-700" : "text-amber-700"}`}>{online ? <Wifi size={16}/> : <CloudOff size={16}/>} {online ? tr("在线", "Online") : tr("离线", "Offline")}</span>
    {pending && <span className="rounded bg-amber-100 px-2 py-1 text-amber-800">{tr("等待同步", "Pending Sync")}</span>}
    {conflict && <span className="inline-flex items-center gap-1 text-rose-700"><AlertTriangle size={16}/>{conflict}</span>}
  </div>;
}

export default function MobileOperationsPage({ initialView }: { initialView?: string }) {
  const { language } = useI18n();
  const tr = (zh: string, en: string) => language === "en-US" ? en : zh;
  const location = useLocation(), navigate = useNavigate();
  const [online, setOnline] = useState(() => navigator.onLine), [pending, setPending] = useState(false), [conflict, setConflict] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  useEffect(() => { const on = () => setOnline(true), off = () => setOnline(false); addEventListener("online", on); addEventListener("offline", off); return () => { removeEventListener("online", on); removeEventListener("offline", off); }; }, []);
  const parts = location.pathname.split("/").filter(Boolean), id = decodeURIComponent(parts.at(-1) || ""), view = initialView || "tasks";
  const run = async (operation: () => Promise<unknown>) => { setError(""); setConflict(""); if (!online) { setPending(true); return; } setBusy(true); try { await operation(); setPending(false); } catch (caught: any) { if (caught?.status === 409 || /conflict|version/i.test(String(caught?.message))) setConflict("Server version changed. Reload before continuing."); else setError(caught instanceof Error ? caught.message : "Operation failed."); } finally { setBusy(false); } };
  return <div className="mx-auto min-w-0 max-w-5xl overflow-x-hidden bg-slate-50" data-testid="mobile-operations-workbench"><StatusBar online={online} pending={pending} conflict={conflict} tr={tr}/>{error && <div className="m-4 rounded-md border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}{view === "tasks" && <TaskInbox onError={setError} tr={tr}/>} {view === "mobile-task" && <TaskDetail id={id}/>} {view === "mobile-po-detail" && <PurchaseOrderDetail id={id} busy={busy} run={run} tr={tr}/>} {view === "mobile-receiving" && <ReceivingHome busy={busy} run={run} tr={tr}/>} {view === "mobile-receiving-detail" && <ReceivingDetail id={id} busy={busy} run={run} tr={tr}/>} {view === "mobile-settlement-detail" && <SettlementDetail id={id} busy={busy} run={run}/>}<div className="h-6"/></div>;
}

function Header({ title, back }: { title: string; back?: boolean }) { const navigate = useNavigate(); return <header className="flex min-h-16 items-center gap-3 px-4 py-3">{back && <button className={secondary} onClick={() => navigate(-1)} aria-label="Back"><ArrowLeft size={18}/></button>}<h1 className="min-w-0 text-xl font-semibold text-slate-950">{title}</h1></header>; }
function Amount({ value }: { value?: { amount?: string; totalAmount?: number; currency?: string } | null }) { return value ? <span className="font-semibold tabular-nums text-slate-950">{value.currency} {value.amount ?? value.totalAmount}</span> : <span className="text-slate-500">Restricted</span>; }

function TaskInbox({ onError, tr }: { onError: (value: string) => void; tr: (zh: string, en: string) => string }) {
  const navigate = useNavigate(), [tasks, setTasks] = useState<Task[]>([]), [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); apiJson<{ items: Task[] }>("/api/mobile/tasks").then((data) => setTasks(data.items)).catch((e) => onError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []);
  return <><Header title={tr("移动任务箱", "Mobile Tasks")}/><div className="flex justify-end px-4"><button className={secondary} onClick={load} aria-label="Refresh tasks"><RefreshCw size={17}/>{tr("刷新", "Refresh")}</button></div><main className="grid min-w-0 gap-3 p-4 md:grid-cols-2">{loading && <p className="text-sm text-slate-500">{tr("加载中...", "Loading...")}</p>}{!loading && !tasks.length && <p className="text-sm text-slate-500">{tr("没有已授权任务。", "No authorized tasks.")}</p>}{tasks.map((task) => <button key={task.taskId} data-testid="mobile-task" className="min-w-0 rounded-md border border-slate-200 bg-white p-4 text-left shadow-sm" onClick={() => navigate(task.deepLink || `/app/mobile/tasks/${encodeURIComponent(task.taskId)}`)}><div className="flex items-start justify-between gap-3"><span className="min-w-0 break-words font-semibold text-slate-950">{task.title}</span><span className="shrink-0 rounded bg-slate-100 px-2 py-1 text-xs text-slate-700">{task.status}</span></div><p className="mt-2 break-words text-sm text-slate-600">{task.summary || tr("详情受限", "Details restricted")}</p><div className="mt-3 flex items-center justify-between gap-3 text-sm"><Amount value={task.amountSummary}/><span className="text-blue-700">{task.availableActions.join(" · ") || tr("查看", "View")}</span></div></button>)}</main></>;
}

function TaskDetail({ id }: { id: string }) { const [item, setItem] = useState<Task | null>(null); useEffect(() => { apiJson<Task>(`/api/mobile/tasks/${encodeURIComponent(id)}`).then(setItem); }, [id]); return <><Header title={item?.title || "Task"} back/><div className="m-4 rounded-md border border-slate-200 bg-white p-4"><p className="text-sm text-slate-600">{item?.summary}</p><div className="mt-4"><Amount value={item?.amountSummary}/></div></div></>; }

function PurchaseOrderDetail({ id, busy, run, tr }: { id: string; busy: boolean; run: (operation: () => Promise<unknown>) => Promise<void>; tr: (zh: string, en: string) => string }) {
  const [po, setPo] = useState<Po | null>(null), load = () => apiJson<Po>(`/api/mobile/purchase-orders/${encodeURIComponent(id)}`).then(setPo); useEffect(() => { void load(); }, [id]);
  const action = (name: "approve" | "reject" | "return-for-revision") => run(async () => { const reason = name === "approve" ? "" : prompt("Reason") || ""; if (name !== "approve" && !reason) return; await apiJson(`/api/mobile/purchase-orders/${encodeURIComponent(id)}/${name}`, { method: "POST", body: JSON.stringify({ expectedVersion: po?.entityVersion, reason, idempotencyKey: mutationId(), clientMutationId: mutationId() }) }); await load(); });
  return <><Header title={po?.orderNumber || tr("采购订单", "Purchase Order")} back/><main className="min-w-0 space-y-4 p-4" data-testid="mobile-po-detail"><section className="rounded-md border border-slate-200 bg-white p-4"><div className="mb-4 flex justify-end"><span className="rounded bg-slate-100 px-2 py-1 text-xs font-medium text-slate-700" data-testid="mobile-po-status">{po?.status}</span></div><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-slate-500">{tr("供应商", "Supplier")}</p><p className="font-medium">{po?.supplierSnapshot?.supplierName || tr("无权限", "Restricted")}</p></div><div className="text-right"><p className="text-sm text-slate-500">{tr("金额", "Amount")}</p><Amount value={po?.amountSummary}/></div></div></section><section className="space-y-2"><h2 className="text-base font-semibold">{tr("明细", "Lines")}</h2>{po?.lines.map((line, index) => <div key={line.id || index} className="min-w-0 rounded-md border border-slate-200 bg-white p-4"><p className="break-words font-medium">{line.sku} · {line.itemNameSnapshot}</p><p className="mt-1 text-sm text-slate-600">{line.quantity} {line.unitSnapshot}</p>{line.amount != null && <p className="mt-2 text-sm tabular-nums">{line.amount}</p>}</div>)}</section><div className="sticky bottom-0 flex flex-wrap gap-2 border-t border-slate-200 bg-slate-50 py-3">{po?.availableActions.includes("return_for_revision") && <button data-testid="mobile-po-return" disabled={busy} className={secondary} onClick={() => void action("return-for-revision")}>{tr("退回修改", "Return")}</button>}{po?.availableActions.includes("reject") && <button data-testid="mobile-po-reject" disabled={busy} className={danger} onClick={() => void action("reject")}>{tr("拒绝", "Reject")}</button>}{po?.availableActions.includes("approve") && <button data-testid="mobile-po-approve" disabled={busy} className={primary} onClick={() => void action("approve")}><Check size={18}/>{tr("批准", "Approve")}</button>}</div></main></>;
}

function ReceivingHome({ busy, run, tr }: { busy: boolean; run: (operation: () => Promise<unknown>) => Promise<void>; tr: (zh: string, en: string) => string }) {
  const navigate = useNavigate(), [search, setSearch] = useState(""), [rows, setRows] = useState<ReceivingPo[]>([]), [warehouses, setWarehouses] = useState<Warehouse[]>([]), [warehouseId, setWarehouseId] = useState(""), [location, setLocation] = useState("A-01"), [quantities, setQuantities] = useState<Record<string, string>>({});
  const find = () => apiJson<{ items: ReceivingPo[]; warehouses: Warehouse[] }>(`/api/mobile/receiving/purchase-orders?search=${encodeURIComponent(search)}`).then((data) => { setRows(data.items); setWarehouses(data.warehouses); setWarehouseId((current) => current || data.warehouses[0]?.id || ""); setQuantities(Object.fromEntries(data.items.flatMap((po) => po.lines.map((line) => [line.id, line.remainingQuantity])))); });
  return <><Header title={tr("移动收货", "Mobile Receiving")}/><main className="min-w-0 space-y-4 p-4" data-testid="mobile-receiving-home"><div className="flex min-w-0 flex-wrap gap-2"><input aria-label={tr("采购订单号", "PO number")} className="min-h-11 min-w-0 flex-1 rounded-md border border-slate-300 px-3" value={search} onChange={(e) => setSearch(e.target.value)} placeholder={tr("采购订单号", "PO number")}/><button data-testid="mobile-receiving-search" className={primary} onClick={() => void find()}><PackageCheck size={18}/>{tr("搜索", "Search")}</button></div>{rows.length > 0 && <div className="grid min-w-0 gap-3 sm:grid-cols-2"><label className="text-sm">{tr("仓库", "Warehouse")}<select aria-label={tr("仓库", "Warehouse")} className="mt-1 min-h-11 w-full min-w-0 rounded-md border border-slate-300 px-3" value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)}><option value="">{tr("选择仓库", "Select warehouse")}</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.code} · {warehouse.name}</option>)}</select></label><label className="text-sm">{tr("库位", "Location")}<input aria-label={tr("库位", "Location")} className="mt-1 min-h-11 w-full min-w-0 rounded-md border border-slate-300 px-3" value={location} onChange={(event) => setLocation(event.target.value)}/></label></div>}{rows.map((po) => <section key={po.id} className="rounded-md border border-slate-200 bg-white p-4" data-testid="mobile-receiving-po"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{po.id}</h2><span className="text-sm text-slate-600">{po.status}</span></div>{po.lines.map((line) => <div key={line.id} className="mt-3 border-t border-slate-100 pt-3 text-sm"><p className="break-words font-medium">{line.sku} · {line.itemName}</p><p className="mt-1 text-slate-600">{tr("剩余", "Remaining")} {line.remainingQuantity} {line.unit}</p><label className="mt-2 block">{tr("本次接收", "Accepted quantity")}<input aria-label={`${tr("接收数量", "Accepted quantity")} ${line.sku}`} inputMode="decimal" className="mt-1 min-h-11 w-full rounded-md border border-slate-300 px-3" value={quantities[line.id] || ""} onChange={(event) => setQuantities({ ...quantities, [line.id]: event.target.value })}/></label><button data-testid="mobile-prepare-receiving" disabled={busy || !warehouseId || !location || !(Number(quantities[line.id]) > 0)} className={`${secondary} mt-2`} onClick={() => void run(async () => { const result = await apiJson<{ entityId: string }>("/api/mobile/receiving/drafts", { method: "POST", body: JSON.stringify({ poId: po.id, warehouseId, lines: [{ purchaseOrderLineId: line.id, acceptedQuantity: quantities[line.id], damagedQuantity: "0", rejectedQuantity: "0", location }], idempotencyKey: mutationId(), clientMutationId: mutationId() }) }); navigate(`/app/mobile/receiving/${encodeURIComponent(result.entityId)}`); })}>{tr("创建收货草稿", "Prepare draft")}</button></div>)}</section>)}</main></>;
}

function ReceivingDetail({ id, busy, run, tr }: { id: string; busy: boolean; run: (operation: () => Promise<unknown>) => Promise<void>; tr: (zh: string, en: string) => string }) {
  const [data, setData] = useState<any>(null), load = () => apiJson(`/api/mobile/receiving/${encodeURIComponent(id)}`).then(setData); useEffect(() => { void load(); }, [id]); const document = data?.receivingDocument;
  const attach = (file: File) => run(async () => { const contentBase64 = await new Promise<string>((resolveFile, reject) => { const reader = new FileReader(); reader.onerror = () => reject(reader.error); reader.onload = () => resolveFile(String(reader.result).split(",")[1] || ""); reader.readAsDataURL(file); }); const staged = await apiJson<{ uploadId: string }>("/api/uploads/stage", { method: "POST", body: JSON.stringify({ fileName: file.name, mimeType: file.type, contentBase64 }) }); await apiJson(`/api/receiving/drafts/${encodeURIComponent(id)}/attachments`, { method: "POST", body: JSON.stringify({ uploadId: staged.uploadId }) }); await load(); });
  return <><Header title={document?.documentNumber || tr("收货", "Receiving")} back/><main className="min-w-0 space-y-4 p-4" data-testid="mobile-receiving-detail"><section className="rounded-md border border-slate-200 bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><span className="font-semibold">{document?.workflowStatus}</span><span className="text-sm text-slate-600">{document?.postingStatus}</span></div></section>{(data?.lines || []).map((line: any) => <section key={line.id} className="rounded-md border border-slate-200 bg-white p-4"><p className="break-words font-medium">{line.sku} · {line.itemName}</p><p className="mt-2 text-sm">{tr("接收", "Accepted")} {line.acceptedQuantity} · {tr("拒收", "Rejected")} {line.rejectedQuantity}</p><p className="mt-1 text-sm text-slate-600">{tr("剩余", "Remaining")} {line.remainingReceivableQuantity}</p></section>)}{document?.postingStatus === "posted" && <section className="rounded-md border border-emerald-200 bg-emerald-50 p-4" data-testid="mobile-inventory-impact"><h2 className="font-semibold">GRN · {document.documentNumber}</h2><p className="mt-2 text-sm">{tr("库存影响", "Inventory impact")}: {(data?.inventoryImpact || []).length}</p></section>}<div className="sticky bottom-0 flex flex-wrap gap-2 border-t border-slate-200 bg-slate-50 py-3">{document?.workflowStatus === "draft" && <label className={secondary}>{tr("上传照片", "Photo attachment")}<input data-testid="mobile-receiving-attachment" className="hidden" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain" onChange={(event) => { const file = event.target.files?.[0]; if (file) void attach(file); }}/></label>}{document?.workflowStatus === "draft" && <button data-testid="mobile-receiving-submit" disabled={busy} className={secondary} onClick={() => void run(async () => { await apiJson(`/api/mobile/receiving/drafts/${encodeURIComponent(id)}/submit`, { method: "POST", body: JSON.stringify({ expectedVersion: document.version, idempotencyKey: mutationId() }) }); await load(); })}><Send size={18}/>{tr("提交", "Submit")}</button>}{document?.postingStatus === "unposted" && document?.workflowStatus !== "draft" && <button data-testid="mobile-receiving-post" disabled={busy} className={primary} onClick={() => void run(async () => { await apiJson(`/api/mobile/receiving/${encodeURIComponent(id)}/preview`); if (!confirm(tr("确认将本次收货过账到库存？", "Post this receiving document to inventory?"))) return; await apiJson(`/api/mobile/receiving/${encodeURIComponent(id)}/post`, { method: "POST", body: JSON.stringify({ expectedVersion: document.version, idempotencyKey: mutationId() }) }); await load(); })}><PackageCheck size={18}/>{tr("过账", "Post")}</button>}</div></main></>;
}

function SettlementDetail({ id, busy, run }: { id: string; busy: boolean; run: (operation: () => Promise<unknown>) => Promise<void> }) {
  const [data, setData] = useState<any>(null), load = () => apiJson(`/api/finance/settlements/${encodeURIComponent(id)}`).then(setData); useEffect(() => { void load(); }, [id]); const actions = useMemo(() => data?.availableActions || [], [data]);
  const act = (action: string) => run(async () => { const reason = ["reject", "cancel"].includes(action) ? prompt("Reason") || "" : ""; if (["reject", "cancel"].includes(action) && !reason) return; if (action === "post" && !confirm("Post this settlement?")) return; await apiJson(`/api/finance/settlements/${encodeURIComponent(id)}/${action}`, { method: "POST", body: JSON.stringify({ expectedVersion: data.version, reason, idempotencyKey: mutationId() }) }); await load(); });
  return <><Header title={data?.settlementNumber || "Settlement"} back/><main className="min-w-0 space-y-4 p-4"><section className="rounded-md border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-slate-500">Workflow</p><p className="font-semibold">{data?.workflowStatus}</p></div><div className="text-right"><p className="text-sm text-slate-500">Cash amount</p><Amount value={data ? { amount: data.cashAmount, currency: data.currency } : null}/></div></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><span>Discount</span><span className="text-right tabular-nums">{data?.discountAmount}</span><span>Advance</span><span className="text-right tabular-nums">{data?.advanceCreatedAmount}</span></div></section><section className="rounded-md border border-slate-200 bg-white p-4"><h2 className="font-semibold">Workflow timeline</h2><p className="mt-2 text-sm text-slate-600">Submitted {data?.submittedAt || "-"}</p><p className="mt-1 text-sm text-slate-600">Approved {data?.approvedAt || "-"}</p><p className="mt-1 text-sm text-slate-600">Posted {data?.postedAt || "-"}</p></section><div className="sticky bottom-0 flex flex-wrap gap-2 border-t border-slate-200 bg-slate-50 py-3">{actions.filter((a: string) => a !== "reverse" && a !== "posting-preview").map((action: string) => <button key={action} disabled={busy} className={action === "post" || action === "approve" ? primary : action === "reject" ? danger : secondary} onClick={() => void act(action)}>{action === "approve" && <ClipboardCheck size={18}/>} {action}</button>)}</div></main></>;
}
